sensor_datadir="${datadir}/phosphor-ipmi-host/sensor"
sensor_yamldir="${datadir}/phosphor-ipmi-host/sensor-yamls"
hostfw_datadir="${datadir}/phosphor-ipmi-fru/hostfw"
bmcfw_datadir="${datadir}/phosphor-ipmi-host/bmcfw"
config_datadir="${datadir}/phosphor-ipmi-host/config"
