#!/bin/sh

if ! lsmod | grep -q sctp && ! modprobe sctp 2>/dev/null; then
        echo "Couldn't load kernel module sctp."
        echo "Test cases testsctp and testcnx will fail."
        echo
fi

cmake  -E cmake_echo_color --cyan "Running tests..."
if ctest --force-new-ctest-process ; then
        echo "PASS: freediameter"
else
        echo "FAIL: freediameter"
fi
