#!/bin/sh
# use target=recheck if you want to recheck failing tests
[ "$target" = "" ] && target=check

# Without --ignore-exit, the tap harness causes any FAILs within a
# test plan to raise ERRORs; this is just noise.
makeargs="LOG_DRIVER_FLAGS=--ignore-exit top_srcdir=$PWD top_builddir=$PWD"

exec make -C tests -k -s $makeargs $target 2>/dev/null
