#! /bin/sh
#  Copyright (c) 2005-2008 Wind River Systems, Inc.
#
# SPDX-License-Identifier: GPL-2.0-only
#

cat << EOF
AC_PREREQ(2.57)
AC_INIT([site_wide],[1.0.0])

EOF

# Disable as endian is set in the default config
#echo AC_C_BIGENDIAN
#echo

if [ -e $1/types ] ; then
  while read type ; do
    echo "AC_CHECK_SIZEOF([$type])"
  done < $1/types

  echo
fi

if [ -e $1/funcs ]; then
  while read func ; do
    echo "AC_CHECK_FUNCS([$func])"
  done < $1/funcs

  echo
fi

if [ -e $1/headers ]; then
  while read header ; do
    echo "AC_CHECK_HEADERS([$header])"
  done < $1/headers

  echo
fi

cat << EOF
AC_OUTPUT
EOF
