#!/bin/bash

# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions

# Power Good Status
power_status() {
    if [ "$(get_gpio "host0-ready")" -eq 1 ] ; then
        echo "on"
    else
        echo "off"
    fi
}

add_sel()
{
    local MSG_ID=$1
    local DEVICE_PATH=$2
    local LOG_TYPE=$3
    local LOG_CONTENT=$4

    /usr/bin/log-create "$MSG_ID" --json \
    "{ \"${LOG_TYPE}\": \"${DEVICE_PATH}\", \"FAILURE_DATA\": \"${LOG_CONTENT}\"}"
}

declare -A ERROR_MAP=(
    ["11"]="S5_PVDD33 Fault(no power good)"
    ["12"]="S5_PVDD18 Fault"
    ["13"]="Wait SLP_S3 Fault"
    ["14"]="S0_PVDDIO Fault"
    ["15"]="PVDDCR_SOC_P0 Fault"
    ["16"]="PVDDCR_CPU0_P0 Fault"
    ["17"]="PVDDCR_CPU1_P0 Fault"

    ["21"]="P12V_E1S_0 Power dropped"
    ["22"]="ASIC0 Power dropped"
    ["23"]="ASIC1 Power dropped"
    ["24"]="ASIC2 Power dropped"
    ["25"]="ASIC3 Power dropped"
    ["26"]="SWB Power dropped"
    ["27"]="PVDDIO_MEM_S3_P0 Power dropped"
    ["28"]="PVDDIO_P0 Power dropped"
    ["29"]="PVDDCR_SOC_P0 Power dropped"
    ["2A"]="PVDDCR_CPU0_P0 Power dropped"
    ["2B"]="PVDDCR_CPU1_P0 Power dropped"

    ["30"]="System Leak"
    ["40"]="System power disable by RMC"
    ["50"]="STBY Fault"
    ["60"]="SLP_S5 Fault"
    ["70"]="No RMC power enable"

    ["80"]="ASIC0 Fault"
    ["81"]="ASIC1 Fault"
    ["82"]="ASIC2 Fault"
    ["83"]="ASIC3 Fault"

    ["90"]="SWB Fault"
)

# Force DC off
force_power_off() {
    if [ "$(power_status)" == "on" ]; then
        trap 'trap - INT TERM; echo "force_power_off: interrupted, restoring power-host-control to 1" | systemd-cat -t power-cmd -p warning; set_gpio power-host-control 1; exit 1' INT TERM
        set_gpio power-host-control 0
        sleep 5
        set_gpio power-host-control 1
        trap - INT TERM
        sleep 1
    fi


    for i in $(seq 1 10)
    do
        sleep 1
        if [ "$(power_status)" == "off" ]; then
            return 0
        fi

        if [ "$i" -eq 10 ]; then
            return 1
        fi
    done

}

# Graceful DC off
graceful_power_off() {
    if [ "$(power_status)" == "on" ]; then
        trap 'trap - INT TERM; echo "graceful_power_off: interrupted, restoring power-host-control to 1" | systemd-cat -t power-cmd -p warning; set_gpio power-host-control 1; exit 1' INT TERM
        set_gpio power-host-control 0
        sleep 5
        set_gpio power-host-control 1
        trap - INT TERM
        sleep 1

        # wait host power off
        for i in $(seq 1 20)
        do
            sleep 1
            if [ "$(power_status)" == "off" ]; then
               break
            fi
        done
    fi
}

# DC on
power_on() {
    if [ "$(power_status)" == "off" ]; then
        set_gpio power-host-control 0
        sleep 1
        set_gpio power-host-control 1
        sleep 1

        for i in $(seq 1 10)
        do
            sleep 1
            if [ "$(power_status)" == "on" ]; then
               return 0
            fi

            if [ "$i" -eq 10 ]; then
                raw=$(i2cget -fy 21 0x33 0x20)
                error_code=${raw:2}
                decode=${ERROR_MAP[$error_code]:-"Unknown Error Code ($error_code)"}
                MSG_ID="xyz.openbmc_project.State.Power.PowerRailFault"
                DEVICE_PATH="/xyz/openbmc_project/inventory/system/board/Santabarbara_MB/power_on_sequence_fail"
                LOG_TYPE="POWER_RAIL"
                LOG_CONTENT="POWER_ON_SEQUENCE_FAIL - [$decode]"
                add_sel $MSG_ID $DEVICE_PATH $LOG_TYPE "$LOG_CONTENT"
               return 1
            fi
        done
    fi
    return 0
}

# Host reset
power_reset() {
    set_gpio CPU0_SYS_RESET_N 0
    sleep 1
    set_gpio CPU0_SYS_RESET_N 1
    sleep 1
    return 0
}
