#!/bin/sh

set -eux

rm -f debug.log child.log

ulimit -c unlimited
ulimit -t 120

cd test
echo foobar > foobar.txt

BASIC_TESTS="auth basic redirect request session socket string-tests \
             stubs uri-tests util-tests"
DAV_TESTS="acl3744 lock oldacl props xml xmlreq"
for t in $BASIC_TESTS $DAV_TESTS
do
    echo "Running $t..."
    if "./$t"
    then
        echo "PASS:$t"
    else
        echo "FAIL:$t"
    fi
done
