#!/bin/sh



if ! nslookup httpbin.org >/dev/null 2>&1 ; then
    trap 'mv /etc/resolv.conf.bak /etc/resolv.conf' INT EXIT
    mv /etc/resolv.conf /etc/resolv.conf.bak    
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
fi

pytest --automake
