#! /usr/bin/env python3
#
# This file was auto-generated by shacl2code 1.0.0. DO NOT MANUALLY MODIFY IT
#
# SPDX-License-Identifier: MIT

from .cmd import main  # noqa: F401
from .model import *  # noqa: F401, F403
