#! /usr/bin/env python3
#
# This file was auto-generated by shacl2code 1.0.0. DO NOT MANUALLY MODIFY IT
#
# SPDX-License-Identifier: MIT

import sys

from .cmd import main

if __name__ == "__main__":
    sys.exit(main())
