#!/bin/bash

STATE="$1"
OS_STANDBY="xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.Standby"
OS_INACTIVE="xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.Inactive"

set_os_status()
{
    busctl set-property xyz.openbmc_project.State.Host0 \
           /xyz/openbmc_project/state/host0 xyz.openbmc_project.State.OperatingSystem.Status \
           OperatingSystemState s "$1"
}

if [ "$STATE" = "assert" ]; then
    set_os_status "$OS_STANDBY"

    # Workaround to Disable BIOSFRB2 ipmi watchdog
    if busctl get-property xyz.openbmc_project.Watchdog /xyz/openbmc_project/watchdog/host0 xyz.openbmc_project.State.Watchdog CurrentTimerUse | grep -q BIOSFRB2; then
        busctl set-property xyz.openbmc_project.Watchdog /xyz/openbmc_project/watchdog/host0 xyz.openbmc_project.State.Watchdog Enabled b false
    fi
elif [ "$STATE" = "deassert" ]; then
    set_os_status "$OS_INACTIVE"
fi

exit 0
