#!/bin/bash

# shellcheck source=meta-facebook/meta-harma/recipes-phosphor/state/phosphor-state-manager/power-cmd
source /usr/libexec/phosphor-state-manager/power-cmd

set_request_host_transition()
{
    busctl set-property xyz.openbmc_project.State.Host0 \
        /xyz/openbmc_project/state/host0 \
        xyz.openbmc_project.State.Host \
        RequestedHostTransition s "$1"
}

cpu_boot_done_val=$(plat_get_gpio "B0_M0_CPU_BOOT_COMPLETE_3V3-I")
echo "cpu_boot_done: $cpu_boot_done_val"

if [[ "$cpu_boot_done_val" == "1" ]]; then
    set_gpio "USB_PWR_EN-O" 0
    set_gpio "E1S_PWR_EN-O" 0
    set_gpio "BMC_SSD0_RST_L-O" 0
    hpm_run_pwr_release_n_check
    pdb_run_pwr_release_n_check

    set_request_host_transition "xyz.openbmc_project.State.Host.Transition.Off"
fi

exit 0
