DESCRIPTION = "Adds support for a predictable and repeatable temporary directory."
HOMEPAGE = "https://github.com/saltstack/pytest-tempdir"
SECTION = "devel/python"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://PKG-INFO;md5=8751a9cf4a70be4f02697a9b89e686ce"

SRC_URI[md5sum] = "f87f2583f5f8aaca7203d57ada3948b5"
SRC_URI[sha256sum] = "65ff815966ea6dfc07ca1b43747c9888a6d883971170e67b16290f9f50d434ea"

inherit pypi
