#!/bin/sh
### BEGIN INIT INFO
# Provides:          cgroups mount
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mount/unmount cgroups
### END INIT INFO

# must start before libvirtd is run
case "$1" in
  start)
        echo -n "Mounting cgroups..."
		/bin/cgroups-mount
        echo "Done"
        ;;
  stop)
        echo -n "Unmounting cgroups..."
		/bin/cgroups-umount
        echo "Done"
        ;;
  *)
        echo "Usage: /etc/init.d/cgroups-init {start|stop}"
        exit 1
        ;;
esac
