#!/bin/bash

# The ALERT pin doesn't trigger when HSC or power module loses ENABLE with VCC present,
# leading to Vout dropping to 0V. Need to record STATUS in this case.

busctl monitor --system --match "type='signal',interface='xyz.openbmc_project.Sensor.Threshold.Critical'" --json=short 2>/dev/null |
while IFS= read -r LINE; do
    script_to_run=""
    arg=""

    # 48V HSC: MEDUSA_HSC0_48V, MEDUSA_HSC1_48V
    if [[ "$LINE" =~ MEDUSA_HSC([0-1])_48V ]]; then
        HSC_NUM=${BASH_REMATCH[1]}
        script_to_run="/usr/libexec/phosphor-gpio-monitor/medusa-hsc-alert"
        arg="$HSC_NUM"

    # Power module: MEDUSA_DELTA0_12V, MEDUSA_DELTA1_12V...
    elif [[ "$LINE" =~ MEDUSA_DELTA([0-3])_12V ]]; then
        DELTA_NUM=${BASH_REMATCH[1]}
        script_to_run="/usr/libexec/phosphor-gpio-monitor/medusa-power-module-fault"
        arg="$DELTA_NUM"

    # 12V HSC: MEDUSA_MB1_HSC_12V, MEDUSA_MB2_HSC_12V...
    elif [[ "$LINE" =~ MEDUSA_MB([1-8])_HSC_12V ]]; then
        MB_NUM=${BASH_REMATCH[1]}
        script_to_run="/usr/libexec/phosphor-gpio-monitor/slot-hsc-fault"
        arg="$MB_NUM"
    fi

    if [[ -n "$script_to_run" ]]; then

        # CALIBRATED_MEDUSA sensors
        if [[ "$LINE" =~ CriticalLowAlarmAsserted || "$LINE" =~ CriticalHighAlarmAsserted ]]; then
            "$script_to_run" "$arg" # Send the event

        # Other MEDUSA sensors - check boolean in JSON payload
        # JSON payload format: [..., true, 22.028] or [..., false, 22.028]
        # "true" means LCR asserted
        elif [[ "$LINE" =~ \"member\":\"ThresholdAsserted\" ]] && [[ "$LINE" =~ ,true, ]]; then
            "$script_to_run" "$arg"
        fi
    fi
done
