# List of known non-reproducible package of the meta-networking layer
# Please keep this list sorted
KNOWN_NON_REPRO_META_NETWORKING = " \
    babeld \
    babeld-dbg \
    dhcp-relay-staticdev \
    ettercap-src \
    freediameter \
    freeradius \
    htpdate-doc \
    libbearssl-staticdev \
    libmosquitto1 \
    libowfat-staticdev \
    libruli-staticdev \
    mosquitto \
    ncftp \
    ndisc6-dbg \
    ndisc6-misc \
    ndisc6-ndisc6 \
    ndisc6-rdisc6 \
    ndisc6-rdnssd \
    ndisc6-rltraceroute6 \
    netsniff-ng-doc \
    ntpsec-src \
    openl2tp \
    postfix-cfg \
    rp-pppoe \
    udpcast-doc \
    unbound-doc \
    znc \
"
