#!/bin/sh
# use target=recheck if you want to recheck failing tests
[ "$target" = "" ] && target=check

# Without --ignore-exit, the tap harness causes any FAILs within a
# test plan to raise ERRORs; this is just noise.
makeargs="LOG_DRIVER_FLAGS=--ignore-exit abs_top_srcdir=$PWD abs_top_builddir=$PWD GREP=grep SED=sed PYTHON=python3"

exec 2> error.log
make -C tests -k -s $makeargs $target
exitcode=$?
if [ -e error.log ]; then
    cat error.log
fi
if [ -e tests/test-suite.log ]; then
    cat tests/test-suite.log
fi

exit $exitcode