#!/bin/sh

set -eux
cd ./test
SKIP_SLOW_TESTS=yes ./test_script | sed -e '/:[[:space:]]ok/s/^/PASS: /' -e '/:[[:space:]]failed/s/^/FAIL: /' -e '/:[[:space:]]skipped/s/^/SKIP: /'
rm -rf /var/volatile/tmp/*e2fsprogs*
rm -f tmp-*
rm -f *.tmp
rm -f *.ok
rm -f *.failed
rm -f *.log
cp ../data/test_data.tmp ./
