vpdlayout_datadir="${datadir}/openpower-fru-vpd/vpdlayout"
inventory_datadir_name="/openpower-fru-inventory/inventory"
inventory_datadir_native="${datadir}${inventory_datadir_name}"
inventory_envdir="${envfiledir}/obmc"
properties_datadir="${datadir}/openpower-fru-vpd/properties"
