#!/bin/sh
#
# Copyright (c) 2018, YADRO
# Author: Alexander Amelkin <a.amelkin@yadro.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ "$(basename -- "$0")" = "setup" ]; then
	echo The script must be sourced, not executed
	exit 1
fi

machine() {
	local target=$1
	local build_dir=$2
	local mfg mach realmach
	for mfg in meta-*; do
		for mach in $mfg/meta-*; do
			if [ -d "$mach" -a -d "$mach/conf/machine" ]; then
				realmach=${mach##*meta-}
				# If a target is specified, then check for a match,
				# otherwise just list what we've discovered
				if [ -n "$target" ]; then
					if [ "$realmach" = "$target" ]; then
						echo Machine $target is $mach
						TEMPLATECONF="$mach/conf" source oe-init-build-env $build_dir
						return
					fi
				else
					echo "$realmach"
				fi
			fi
		done
	done

	[ -n "$target" ] && echo "No such machine!"
}

if [ -z "$1" ]; then
	echo Target machine must be specified. Use one of:
	echo
	(echo qemuarm; machine) | sort
elif [ "$1" = "qemuarm" ]; then
	source openbmc-env
else
	bld_dir=$2
	if [ -z "$2" ]; then
		bld_dir="build"
	fi
	machine $1 $bld_dir
fi

