#!/bin/sh

# Start all init scripts in /etc/rcS.d and /etc/rc5.d
# executing them in numerical order.
#

for i in /etc/rcS.d/S??* /etc/rc5.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

