#!/bin/sh
# Wrapper script for real llvm-config. Simply calls

if [ $WANT_LLVM_RELEASE ]; then
	exec `dirname $0`/${TARGET_PREFIX}llvm-config$WANT_LLVM_RELEASE ${@}
else
	echo "To use llvm-common WANT_LLVM_RELEASE needs to be exported."
	echo "For example if this is being called through a recipe:"
	echo "export WANT_LLVM_RELEASE=\"3.3\""
	exit 1
fi
