# Yosemite5 AST2700 config file.

# Uses linux-dummy and temporary workarounds until formal AST2700
# upstream support is available.
YV5A7_ASSUMED_PROVIDERS ?= "u-boot-fw-utils-aspeed-sdk"
YV5A7_IMAGE_FSTYPES_REMOVE ?= "cpio.zst.fitImage mtd-static-norootfs"
PREFERRED_PROVIDER_virtual/kernel = "linux-dummy"
ASSUME_PROVIDED:append = " ${YV5A7_ASSUMED_PROVIDERS}"
RPROVIDES:base-files:append = " ${YV5A7_ASSUMED_PROVIDERS}"
IMAGE_FSTYPES:remove = "${YV5A7_IMAGE_FSTYPES_REMOVE}"

# Kernel Build Settings
KMACHINE = "aspeed"
KERNEL_DEVICETREE = "aspeed/ast2700-evb.dtb"
KBUILD_DEFCONFIG = "aspeed_g7_defconfig"

# CALIPTRA Settings
CALIPTRA_FW_BINARY = "caliptra-fw.bin"
CALIPTRA_MANIFEST_FLASH_IMAGE = "ast2700-manifest-flash.bin"

# U-Boot Build Settings
UBOOT_MACHINE = "evb-ast2700_defconfig"
UBOOT_DEVICETREE = "ast2700-evb"

OBMC_COMPATIBLE_NAMES = "com.meta.Hardware.BMC.Model.Yosemite5a7"

require conf/distro/include/phosphor-static-norootfs.inc
require conf/distro/include/pldm.inc
require conf/machine/include/ast2700.inc
require conf/machine/include/facebook-compute-amd.inc
require conf/machine/include/facebook-compute-singlehost.inc
require conf/machine/include/facebook-ncsi-nic.inc
require conf/machine/include/obmc-bsp-common.inc
require conf/machine/include/tpm2.inc

VIRTUAL-RUNTIME_obmc-host-state-manager = "phosphor-state-manager-host"
VIRTUAL-RUNTIME_obmc-chassis-state-manager = "phosphor-state-manager-chassis"

# Note: Yosemite5 does not actually contain two chassis. Currently,
# we use an additional "chassis" to enable the required functionality.
# 0 -> chassis, 1 -> tray
OBMC_CHASSIS_INSTANCES = "0 1"

FIT_KERNEL_COMP_ALG:df-obmc-static-norootfs ?= "gzip"
FIT_KERNEL_COMP_ALG_EXTENSION:df-obmc-static-norootfs ?= ".gz"

IMAGE_FSTYPES:remove = "mtd-static mtd-static-alltar mtd-static-tar"

FLASH_SIZE = "131072"
FLASH_MANIFEST_OFFSET:flash-131072 = "4088"
FLASH_UBOOT_ENV_OFFSET:flash-131072 = "4096"
FLASH_KERNEL_OFFSET:flash-131072 = "4224"
