#!/usr/bin/env python3
#
# Wrapper around 'git' that doesn't think we are root

import os
import shutil
import sys

os.environ['PSEUDO_UNLOAD'] = '1'

# calculate path to the real 'git'
path = os.environ['PATH']
path = path.replace(os.path.dirname(sys.argv[0]), '')
real_git = shutil.which('git', path=path)

if len(sys.argv) == 1:
    os.execl(real_git, 'git')

os.execv(real_git, sys.argv)
