#!/bin/sh
cd testsuite

echo -n "---- test-lz4 ----"
make -C tests test-lz4  > /dev/null 2>&1

if [ $? -eq 0 ]; then
  echo "PASS"
else
  echo "FAIL"
fi

echo -n "---- test-fasttest ----"
make -C tests test-fasttest  > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "PASS"
else
  echo "FAIL"
fi

echo -n "---- test-frametest ----"
make -C tests test-frametest > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "PASS"
else
  echo "FAIL"
fi

echo -n "---- test-fullbench ----"
make -C tests test-fullbench >  /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "PASS"
else
  echo "FAIL"
fi

echo -n "---- test-fuzzer ----"
make -C tests test-fuzzer >  /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "PASS"
else
  echo "FAIL"
fi
