#!/bin/sh
### BEGIN INIT INFO
# Provides:          halt
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      0
# Short-Description: Execute the halt command.
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# See if we need to cut the power.
if test -x /etc/init.d/ups-monitor
then
	/etc/init.d/ups-monitor poweroff
fi

# Don't shut down drives if we're using RAID.
hddown="-h"
if grep -qs '^md.*active' /proc/mdstat
then
	hddown=""
fi

halt SED_HALTARGS -p $hddown

: exit 0
