#!/bin/sh

cd fftw
/usr/bin/perl -w ./check.pl  -r -c=30 -v `pwd`/bench
fftw_result=$?
cd ../fftwf
/usr/bin/perl -w ./check.pl  -r -c=30 -v `pwd`/benchf
fftwf_result=$?
cd ../fftwl
/usr/bin/perl -w ./check.pl  -r -c=30 -v `pwd`/benchl
fftwl_result=$?

if [ $fftw_result  = "0" ]; then
	echo "PASS: fftw"
else
	echo "FAIL: fftw"
fi
if [ $fftwf_result = "0" ]; then
	echo "PASS: fftwf"
else
	echo "FAIL: fftwf"
fi
if [ $fftwl_result = "0" ]; then
	echo "PASS: fftwl"
else
	echo "FAIL: fftwl"
fi
