#!/bin/sh

DAEMON=/usr/libexec/iwd
PIDFILE=/var/run/iwd.pid
DESC="iNet wireless daemon"

if [ -f /etc/default/iwd ] ; then
	. /etc/default/iwd
fi

set -e

do_start() {
	start-stop-daemon --start --background --name iwd --quiet --exec $DAEMON
}

do_stop() {
	start-stop-daemon --stop --oknodo --name iwd --quiet
}

case "$1" in
  start)
	echo "Starting $DESC"
	do_start
	;;
  stop)
	echo "Stopping $DESC"
	do_stop
	;;
  restart|force-reload)
	echo "Restarting $DESC"
	do_stop
	sleep 1
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0