# List of known non-reproducible package of the meta-python layer
# Please keep this list sorted
KNOWN_NON_REPRO_META_PYTHON = " \
    python3-evdev \
    python3-evdev-dbg \
    python3-evdev-src \
    python3-frozenlist \
    python3-frozenlist-dbg \
    python3-kivy-src \
    python3-pandas \
    python3-pandas-dbg \
    python3-pandas-src \
    python3-pybind11-json-dev \
    python3-pycocotools-src \
    python3-pydantic-core \
    python3-pynacl \
    python3-pynacl-dbg \
    python3-pynacl-src \
    python3-pyproj \
    python3-pyproj-dbg \
    python3-pyproj-src \
    python3-pyzmq \
    python3-yarl \
    python3-yarl-dbg \
"
