mux-gpios = BLADE_UART_SEL0,BLADE_UART_SEL1,BLADE_UART_SEL2,BLADE_UART_SEL3
baud = 57600
console-id = ttyS5
log-timestamp = 1

[compute_blade_1]
mux-index = 0
logfile = /var/log/obmc-console-compute_blade_1.log
logfile-timestamped = /var/log/obmc-console-compute_blade_1-timestamped.log

[compute_blade_2]
mux-index = 1
logfile = /var/log/obmc-console-compute_blade_2.log
logfile-timestamped = /var/log/obmc-console-compute_blade_2-timestamped.log

[compute_blade_3]
mux-index = 2
logfile = /var/log/obmc-console-compute_blade_3.log
logfile-timestamped = /var/log/obmc-console-compute_blade_3-timestamped.log

[compute_blade_4]
mux-index = 3
logfile = /var/log/obmc-console-compute_blade_4.log
logfile-timestamped = /var/log/obmc-console-compute_blade_4-timestamped.log

[compute_blade_5]
mux-index = 4
logfile = /var/log/obmc-console-compute_blade_5.log
logfile-timestamped = /var/log/obmc-console-compute_blade_5-timestamped.log

[compute_blade_6]
mux-index = 5
logfile = /var/log/obmc-console-compute_blade_6.log
logfile-timestamped = /var/log/obmc-console-compute_blade_6-timestamped.log

[compute_blade_7]
mux-index = 6
logfile = /var/log/obmc-console-compute_blade_7.log
logfile-timestamped = /var/log/obmc-console-compute_blade_7-timestamped.log

[compute_blade_8]
mux-index = 7
logfile = /var/log/obmc-console-compute_blade_8.log
logfile-timestamped = /var/log/obmc-console-compute_blade_8-timestamped.log

[compute_blade_9]
mux-index = 8
logfile = /var/log/obmc-console-compute_blade_9.log
logfile-timestamped = /var/log/obmc-console-compute_blade_9-timestamped.log

[compute_blade_10]
mux-index = 9
logfile = /var/log/obmc-console-compute_blade_10.log
logfile-timestamped = /var/log/obmc-console-compute_blade_10-timestamped.log

[compute_blade_11]
mux-index = 10
logfile = /var/log/obmc-console-compute_blade_11.log
logfile-timestamped = /var/log/obmc-console-compute_blade_11-timestamped.log

[compute_blade_12]
mux-index = 11
logfile = /var/log/obmc-console-compute_blade_12.log
logfile-timestamped = /var/log/obmc-console-compute_blade_12-timestamped.log

[compute_blade_13]
mux-index = 12
logfile = /var/log/obmc-console-compute_blade_13.log
logfile-timestamped = /var/log/obmc-console-compute_blade_13-timestamped.log

[compute_blade_14]
mux-index = 13
logfile = /var/log/obmc-console-compute_blade_14.log
logfile-timestamped = /var/log/obmc-console-compute_blade_14-timestamped.log

[compute_blade_15]
mux-index = 14
logfile = /var/log/obmc-console-compute_blade_15.log
logfile-timestamped = /var/log/obmc-console-compute_blade_15-timestamped.log

[compute_blade_16]
mux-index = 15
logfile = /var/log/obmc-console-compute_blade_16.log
logfile-timestamped = /var/log/obmc-console-compute_blade_16-timestamped.log
