#!/bin/sh

srcdir=/usr/lib/pv/ptest       
export srcdir                      
                        
source tests/test-env.sh
               
num_fail=0

# all pv tests are capitalized
for test in tests/[A-Z]*
do
    ./"$test" \
         && echo "PASS: $test" \
         || {
            echo "FAIL: $test"
            num_fail=$(( ${num_fail} + 1))
         }

done

exit $num_fail
