#!/bin/sh

en_US=`locale -a | grep en_US*`
fr_FR=`locale -a | grep fr_FR*`
de_DE=`locale -a | grep de_DE*`

if [ -z "$en_US" ]
then
        echo "Warning: The en_US* locales is needed to run the intl.tests, please add it."
fi
 
if [ -z "$fr_FR" ]
then
        echo "Warning: The fr_FR* locales is needed to run the intl.tests, please add it."
fi
 
if [ -z "$de_DE" ]
then
        echo "Warning: The de_DE* locales is needed to run the intl.tests, please add it."
fi

useradd bashtest
chown -R bashtest:bashtest tests
setpriv --reuid bashtest --rgid bashtest --clear-groups --reset-env $(dirname "$0")/run-bash-ptests
chown -R root:root tests
userdel -r bashtest
