#!/bin/bash -e
# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions

# 88E6393X PWRGD gpio number
CHIP_PWRGD=100

set_bmc_ready()
{
    local bmc_ready="/sys/class/leds/bmc_ready_noled/brightness"
    echo 1 > ${bmc_ready}

    return 0
}

#Meta request Quanta thermal team set fixed PWM to 70% before fan table finished.
set_fan_pwm_fixed()
{
    echo $((255 * 70/100 )) >/sys/class/i2c-dev/i2c-18/device/18-0020/hwmon/hwmon*/pwm1
    echo $((255 * 70/100 )) >/sys/class/i2c-dev/i2c-18/device/18-0020/hwmon/hwmon*/pwm3
    echo $((255 * 70/100 )) >/sys/class/i2c-dev/i2c-18/device/18-0020/hwmon/hwmon*/pwm4
    echo $((255 * 70/100 )) >/sys/class/i2c-dev/i2c-18/device/18-0020/hwmon/hwmon*/pwm6
}

power_on_led_init() {
    systemctl start obmc-led-group-start@power_on.service
}

mdio_LED_setting_for_marvell_chip()
{
    ## To configure the SFP+ LED to blink based on Link/Act/Speed
    # LED 0 & 1 Control for Port 9
    led_port9=$(mdio 1* 10 0x16)

    # Set the 15th bit to 1 for updating
    led_port9=$((led_port9 | 0x8000))

    # Clear the 7~4th bits for Port 10 Link/Act/Speed by blinking
    led_port9=$((led_port9 & ~0x00F0))

    # Write to the register
    mdio 1* 10 0x16 $led_port9
}

# Change the i2c path to the eeprom to the 88E6393X
set_gpio FM_88E6393X_BIN_UPDATE_EN_N 1
# Sleep 2s
sleep 2s
# Enable the pwrgd to the 88E6393X
# Temp setting by gpio group and number directly, need to discuss whether need to define in the DTS (long term solution)
gpioset 0 "$CHIP_PWRGD"=1

set_fan_pwm_fixed
set_bmc_ready
power_on_led_init
mdio_LED_setting_for_marvell_chip

exit 0
