#!/bin/sh

# Upstream "fast" tests take about 5 minutes and currently do not run cleanly
# (tests/cover and tests/pytest)
# https://github.com/HypothesisWorks/hypothesis/tree/master/hypothesis-python/tests
# https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/scripts/basic-test.sh#L18
#
# Instead we run two test suites imported from examples/

pytest --automake
