#!/bin/sh

# The tests contain hard-coded relative paths and must be
# executed from $pdir.
#
pdir=`dirname $0`
cd ${pdir}
for i in t/*.t ; do
	perl ${i} 1>/dev/null 2>&1;
	if [ $? == 0 ]; then
		echo PASS: $i;
	else
		echo FAIL: $i;
	fi;
done
