diff --git a/unix/Makefile.am b/unix/Makefile.am
index a792147..a108bc6 100644
--- a/unix/Makefile.am
+++ b/unix/Makefile.am
@@ -11,13 +11,13 @@ libOpenIPMIpthread_la_SOURCES = posix_thread_os_hnd.c selector.c
 libOpenIPMIpthread_la_LIBADD = -lpthread $(GDBM_LIB) \
 	$(top_builddir)/utils/libOpenIPMIutils.la
 libOpenIPMIpthread_la_LDFLAGS = -rdynamic -version-info $(LD_VERSION) \
-	-Wl,-Map -Wl,libOpenIPMIpthread.map -L$(libdir)
+	-Wl,-Map -Wl,libOpenIPMIpthread.map
 
 libOpenIPMIposix_la_SOURCES = posix_os_hnd.c selector.c
 libOpenIPMIposix_la_LIBADD = $(top_builddir)/utils/libOpenIPMIutils.la \
 	$(GDBM_LIB)
 libOpenIPMIposix_la_LDFLAGS = -rdynamic -version-info $(LD_VERSION) \
-	-Wl,-Map -Wl,libOpenIPMIposix.map -L$(libdir)
+	-Wl,-Map -Wl,libOpenIPMIposix.map
 
 noinst_HEADERS = heap.h
 
