#!/bin/bash -eur
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-
#
# Find python modules uncovered by oe-seltest
#
# Copyright (c) 2016, Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Author: Ed Bartosh <ed.bartosh@linux.intel.com>
#

if [ ! "$#" -eq 1 -o -t 0 ] ; then
    echo 'Usage: coverage report | ./scripts/contrib/uncovered <dir>' 1>&2
    exit 1
fi

path=$(readlink -ev $1)

if [ ! -d "$path" ] ; then
    echo "directory $1 doesn't exist" 1>&2
    exit 1
fi

diff -u <(grep "$path" | grep -v '0%$' | cut -f1 -d: | sort) \
     <(find $path | xargs file | grep 'Python script' | cut -f1 -d:| sort) | \
     grep "^+$path" | cut -c2-
