PHOSPHOR_DBUS_MONITOR_CONFIGS:append:ibm-ac-server = " fan-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS:append:ibm-ac-server = " thermal-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS:append:ibm-ac-server = " power-supply-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS:append:ibm-ac-server = " events-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS:append:ibm-ac-server = "${@bb.utils.contains('DISTRO_FEATURES', 'phosphor-no-snmp', '', ' snmp-policy', d)}"
PHOSPHOR_DBUS_MONITOR_CONFIGS:append:ibm-enterprise = "${@bb.utils.contains('DISTRO_FEATURES', 'phosphor-no-snmp', '', ' snmp-policy', d)}"
PHOSPHOR_DBUS_MONITOR_CONFIGS:append:sbp1 = " bios-policy"