PHOSPHOR_DBUS_MONITOR_CONFIGS_append_ibm-ac-server = " fan-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_ibm-ac-server = " thermal-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_ibm-ac-server = " power-supply-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_ibm-ac-server = " events-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_mihawk = " fan-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_mihawk = " thermal-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_mihawk = " power-supply-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_mihawk = " events-policy"
