#!/bin/bash

# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions

# Power Good Status
power_status() {
    if [ "$(get_gpio "host0-ready")" -eq 1 ] && [ "$(get_gpio "power-card-enable")" -eq 0 ] ; then
        echo "on"
    else
        echo "off"
    fi
}

# Force DC off
force_power_off() {
    if [ "$(power_status)" == "on" ]; then
        set_gpio power-host-control 0
        sleep 6
        set_gpio power-host-control 1
        sleep 1
    fi
}

# Graceful DC off
graceful_power_off() {
    if [ "$(power_status)" == "on" ]; then
        set_gpio power-host-control 0
        sleep 1
        set_gpio power-host-control 1
        sleep 1

        # wait host power off
        sleep 10
    fi
}

# DC on
power_on() {
    if [ "$(power_status)" == "off" ]; then
        set_gpio power-host-control 0
        sleep 1
        set_gpio power-host-control 1
        sleep 1

        for i in $(seq 1 10)
        do
            sleep 1
            if [ "$(power_status)" == "on" ]; then
               return 0
            fi

            if [ "$i" -eq 10 ]; then
               return 1
            fi
        done
    fi
    return 0
}

# Host reset
power_reset() {
    set_gpio reset-control 0
    sleep 1
    set_gpio reset-control 1
    sleep 1
    return 0
}
