#!/bin/bash

# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions

# Power Good Status
power_status() {
    if [ "$(get_gpio "host0-ready")" -eq 1 ]; then
        echo "on"
    else
        echo "off"
    fi
}

# DC off
power_off() {
    if [ "$(power_status)" == "on" ]; then
        echo "Set Host Power Off"
        set_gpio power-host-control 0
        sleep 6
        set_gpio power-host-control 1
        sleep 1
    fi
}

# DC on
power_on() {
    if [ "$(power_status)" == "off" ]; then
        set_gpio power-host-control 0
        sleep 1
        set_gpio power-host-control 1
        sleep 1

        for i in $(seq 1 10)
        do
            sleep 1
            if [ "$(power_status)" == "on" ]; then

               echo "Set Host Power On"
               return 0
            fi

            if [ "$i" -eq 10 ]; then
               echo "Set Host Power On Fail"
               return 1
            fi
        done
    fi
    return 0
}

# Host reset
power_reset() {
    echo "Set Host Reset"
    set_gpio reset-control 0
    sleep 1
    set_gpio reset-control 1
    sleep 1
}
