#!/bin/bash
if [ -z "$1" ]; then
    echo "Usage: $0 <i2c-dev>" >&2
    exit 1
fi

I2C_DEV="$1"
readonly MAX_VOLT=10
readonly MIN_VOLT=2
readonly MAX_FLOWRATE=333               # UNIT: LPM
readonly DEFAULT_FLOWRATE=150           # UNIT: LPM
readonly VALVE_CONFIG_FILE="/var/lib/valvemonitor/valve-config.json"

BUS=${I2C_DEV%%-*}
ADDR=${I2C_DEV##*-}

if ! i2cget -y -f "$BUS" "0x$ADDR" 0x00 >/dev/null 2>&1; then
    echo "[$I2C_DEV] I2C device not responding" >&2
    exit 1
fi

flowrate_to_volt() {
    local flowrate="$1"
    awk -v flowrate="$flowrate" \
        -v max_volt="$MAX_VOLT" \
        -v min_volt="$MIN_VOLT" \
        -v max_flowrate="$MAX_FLOWRATE" \
        'BEGIN {print (flowrate/max_flowrate)*(max_volt-min_volt)+min_volt}'
}

declare -A ADDR_MAP=(
    ["000c"]="SupplyValve2_2"
    ["000e"]="SupplyValve2_3"
    ["000f"]="SupplyValve2_1"
)

FLOWRATE="$DEFAULT_FLOWRATE"

VALVE_NAME="${ADDR_MAP[$ADDR]}"
if [ -z "$VALVE_NAME" ]; then
    echo "[$I2C_DEV] Bus addr '$ADDR' not found in mapping table, using default flowrate: ${DEFAULT_FLOWRATE} LPM" >&2
elif [ ! -f "$VALVE_CONFIG_FILE" ]; then
    echo "[$I2C_DEV] Valve config file '$VALVE_CONFIG_FILE' not found, using default flowrate: ${DEFAULT_FLOWRATE} LPM" >&2
else
    _flowrate=$(jq --arg name "$VALVE_NAME" \
            '.Valves[] | select(.Name == $name) | .FlowRate' \
        "$VALVE_CONFIG_FILE")
    if [[ "$_flowrate" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
        FLOWRATE="$_flowrate"
    else
        echo "[$I2C_DEV] '$VALVE_NAME' not found in $VALVE_CONFIG_FILE, using default flowrate: ${DEFAULT_FLOWRATE} LPM" >&2
    fi
fi
echo "[$I2C_DEV] Flowrate set to: ${FLOWRATE} LPM" >&2
VOLT=$(flowrate_to_volt "$FLOWRATE")

dac_volt_set() {
    local dev="$1" volt="$2"
    local iio raw

    if ! iio=$(ls -d /sys/bus/i2c/devices/"$dev"/iio:device* 2>/dev/null); then
        echo "[$dev] IIO device not ready" >&2
        return 1
    fi

    raw=$(awk -v r="$volt" 'BEGIN { printf "%d", (r-1.05)/0.008826979 }')
    [ "$raw" -lt 0 ] && raw=0
    echo "[$dev] volt=$volt raw=$raw"

    if ! echo 0 > "$iio/out_voltage0_powerdown" 2>/dev/null; then
        echo "[$dev] write powerdown failed" >&2
        return 1
    fi

    if ! echo "$raw" > "$iio/out_voltage0_raw" 2>/dev/null; then
        echo "[$dev] write raw failed" >&2
        return 1
    fi

    echo "[$dev] DAC set request sent"
    return 0
}

retry=5
while [ $retry -gt 0 ]; do
    if dac_volt_set "$I2C_DEV" "$VOLT"; then
        echo "[$I2C_DEV] DAC init success"
        exit 0
    fi
    retry=$((retry - 1))
    sleep 0.1
done

echo "[$I2C_DEV] DAC init failed after retry" >&2
exit 1