RDEPENDS_${PN}_append_ibm-ac-server = " avsbus-control"
RDEPENDS_${PN}_append_witherspoon = " vrm-control"
RDEPENDS_${PN}_append_ibm-ac-server = " power-workarounds"
RDEPENDS_${PN}_append_mihawk = " avsbus-control"
RDEPENDS_${PN}_append_mihawk = " vrm-control"
