RDEPENDS:${PN}:append:ibm-ac-server = " avsbus-control"
RDEPENDS:${PN}:append:witherspoon = " vrm-control"
RDEPENDS:${PN}:append:ibm-ac-server = " power-workarounds"
RDEPENDS:${PN}:append:mihawk = " avsbus-control"
RDEPENDS:${PN}:append:mihawk = " vrm-control"
