#!/bin/sh

"$INIT_HOME/enable-devmem"

MEDIA_DIR="/run/media"
mkdir -p $MEDIA_DIR

# Detect boot flash source
WDTA_SCRATCH_VAL=$(printf "%d" "$(/sbin/devmem 0x14c3744c)")
echo $(( (WDTA_SCRATCH_VAL & 2) >> 1 )) > "$MEDIA_DIR/slot"
