[Unit]
Description=%i Console Server
ConditionPathExists=/etc/obmc-console/server.%i.conf
ConditionPathExists=/dev/tcu-muxer/%i

[Service]
# Instance ID is the VUART basename
ExecStart=
ExecStart=/usr/sbin/obmc-console-server --config /etc/obmc-console/server.%i.conf /dev/tcu-muxer/%i
SyslogIdentifier=%i-console-server
Restart=always
