LICENSE += "& BSD-3-Clause & MIT"

LIC_FILES_CHKSUM += "\
    file://pkg/mod/cel.dev/expr@v0.24.0/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/cloud.google.com/go/auth/oauth2adapt@v0.2.8/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/cloud.google.com/go/auth@v0.16.2/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/cloud.google.com/go/bigquery@v1.69.0/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/cloud.google.com/go/compute/metadata@v0.7.0/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/cloud.google.com/go/iam@v1.5.2/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/cloud.google.com/go/monitoring@v1.24.2/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/cloud.google.com/go/spanner@v1.82.0/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/cloud.google.com/go/storage@v1.55.0/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/cloud.google.com/go@v0.121.3/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/github.com/!google!cloud!platform/grpc-gcp-go/grpcgcp@v1.5.2/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/detectors/gcp@v1.28.0/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/metric@v0.52.0/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/internal/resourcemapping@v0.52.0/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/github.com/!vivid!cortex/gohistogram@v1.0.0/LICENSE;md5=13880cf5821e7668762c89bb8a6045d3;spdx=MIT \
    file://pkg/mod/github.com/apache/arrow/go/v15@v15.0.2/LICENSE.txt;md5=9046099156f93a7f0ac340571476a58b;spdx=Unknown \
    file://pkg/mod/github.com/beorn7/perks@v1.0.1/LICENSE;md5=0d0738f37ee8dc0b5f88a32e83c60198;spdx=MIT \
    file://pkg/mod/github.com/cespare/xxhash/v2@v2.3.0/LICENSE.txt;md5=802da049c92a99b4387d3f3d91b00fa9;spdx=MIT \
    file://pkg/mod/github.com/cncf/xds/go@v0.0.0-20250501225837-2ac532fd4443/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/github.com/envoyproxy/go-control-plane/envoy@v1.32.4/LICENSE;md5=e3fc50a88d0a364313df4b21ef20c29e;spdx=Apache-2.0 \
    file://pkg/mod/github.com/envoyproxy/protoc-gen-validate@v1.2.1/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/github.com/felixge/httpsnoop@v1.0.4/LICENSE.txt;md5=684da2bf3eed8fc8860e75ad84638225;spdx=MIT \
    file://pkg/mod/github.com/go-jose/go-jose/v4@v4.1.0/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/github.com/go-logr/logr@v1.4.3/LICENSE;md5=e3fc50a88d0a364313df4b21ef20c29e;spdx=Apache-2.0 \
    file://pkg/mod/github.com/go-logr/stdr@v1.2.2/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/github.com/goccy/go-json@v0.10.5/LICENSE;md5=33a07164132d795872805bfc53f6097d;spdx=MIT \
    file://pkg/mod/github.com/golang/groupcache@v0.0.0-20241129210726-2c02b8208cf8/LICENSE;md5=19cbd64715b51267a47bf3750cc6a8a5;spdx=Apache-2.0 \
    file://pkg/mod/github.com/google/flatbuffers@v25.1.24+incompatible/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/github.com/google/s2a-go@v0.1.9/LICENSE.md;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/github.com/google/uuid@v1.6.0/LICENSE;md5=88073b6dd8ec00fe09da59e0b6dfded1;spdx=BSD-3-Clause \
    file://pkg/mod/github.com/googleapis/enterprise-certificate-proxy@v0.3.6/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/github.com/googleapis/gax-go/v2@v2.14.2/LICENSE;md5=0dd48ae8103725bd7b401261520cdfbb;spdx=BSD-3-Clause \
    file://pkg/mod/github.com/ianlancetaylor/demangle@v0.0.0-20250625212726-86fd2c0a1a74/LICENSE;md5=81729dc66d48cba483290ca39318923d;spdx=Unknown \
    file://pkg/mod/github.com/klauspost/compress@v1.18.0/LICENSE;md5=d0fd9ebda39468b51ff4539c9fbb13a8;spdx=BSD-3-Clause \
    file://pkg/mod/github.com/munnerz/goautoneg@v0.0.0-20191010083416-a7dc8b61c822/LICENSE;md5=0c241922fc69330e2e5590de114f3bf5;spdx=BSD-3-Clause \
    file://pkg/mod/github.com/pierrec/lz4/v4@v4.1.18/LICENSE;md5=09ece85f3c312a63b522bfc6ebd44943;spdx=Unknown \
    file://pkg/mod/github.com/prometheus/client_golang@v1.23.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/github.com/prometheus/client_model@v0.6.2/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/github.com/prometheus/common@v0.65.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/github.com/prometheus/procfs@v0.16.1/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/github.com/sergi/go-diff@v1.4.0/APACHE-LICENSE-2.0;md5=2ee41112a44fe7014dce33e26468ba93;spdx=Apache-2.0 \
    file://pkg/mod/github.com/spiffe/go-spiffe/v2@v2.5.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/github.com/ulikunitz/xz@v0.5.12/LICENSE;md5=3c82255323cf3d48815acdbf9068b715;spdx=Unknown \
    file://pkg/mod/github.com/zeebo/errs@v1.4.0/LICENSE;md5=84914ab36fc0eb48edbaa53e66e8d326;spdx=MIT \
    file://pkg/mod/github.com/zeebo/xxh3@v1.0.2/LICENSE;md5=acf3e468cbf92b877ec5cdff11749253;spdx=Unknown \
    file://pkg/mod/go.opencensus.io@v0.24.0/LICENSE;md5=175792518e4ac015ab6696d16c4f607e;spdx=Apache-2.0 \
    file://pkg/mod/go.opentelemetry.io/auto/sdk@v1.1.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/go.opentelemetry.io/contrib/detectors/gcp@v1.36.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.61.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.61.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/go.opentelemetry.io/otel/metric@v1.36.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/go.opentelemetry.io/otel/sdk/metric@v1.36.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/go.opentelemetry.io/otel/sdk@v1.36.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/go.opentelemetry.io/otel/trace@v1.36.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/go.opentelemetry.io/otel@v1.36.0/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327;spdx=Apache-2.0 \
    file://pkg/mod/golang.org/x/crypto@v0.40.0/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a;spdx=BSD-3-Clause \
    file://pkg/mod/golang.org/x/exp@v0.0.0-20250711185948-6ae5c78190dc/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a;spdx=BSD-3-Clause \
    file://pkg/mod/golang.org/x/net@v0.42.0/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a;spdx=BSD-3-Clause \
    file://pkg/mod/golang.org/x/oauth2@v0.30.0/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a;spdx=BSD-3-Clause \
    file://pkg/mod/golang.org/x/sync@v0.16.0/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a;spdx=BSD-3-Clause \
    file://pkg/mod/golang.org/x/sys@v0.34.0/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a;spdx=BSD-3-Clause \
    file://pkg/mod/golang.org/x/text@v0.27.0/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a;spdx=BSD-3-Clause \
    file://pkg/mod/golang.org/x/time@v0.12.0/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a;spdx=BSD-3-Clause \
    file://pkg/mod/golang.org/x/xerrors@v0.0.0-20240903120638-7835f813f4da/LICENSE;md5=e828fb91fe88d9e5d620842cf8bd81b0;spdx=Unknown \
    file://pkg/mod/google.golang.org/api@v0.237.0/LICENSE;md5=a651bb3d8b1c412632e28823bb432b40;spdx=BSD-3-Clause \
    file://pkg/mod/google.golang.org/genproto/googleapis/api@v0.0.0-20250603155806-513f23925822/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20250603155806-513f23925822/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/google.golang.org/genproto@v0.0.0-20250603155806-513f23925822/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/google.golang.org/grpc@v1.73.0/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
    file://pkg/mod/google.golang.org/protobuf@v1.36.6/LICENSE;md5=02d4002e9171d41a8fad93aa7faf3956;spdx=BSD-3-Clause \
"

LIC_FILES_CHKSUM_HOST = "\
    file://pkg/mod/github.com/golang/protobuf@v1.5.4/LICENSE;md5=939cce1ec101726fa754e698ac871622;spdx=BSD-3-Clause \
    file://pkg/mod/github.com/gorilla/handlers@v1.5.2/LICENSE;md5=c30eee78985cf2584cded5f89ba3d787;spdx=Unknown \
    file://pkg/mod/google.golang.org/appengine/v2@v2.0.6/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57;spdx=Apache-2.0 \
"

LIC_FILES_CHKSUM:class-native += "${LIC_FILES_CHKSUM_HOST}"
LIC_FILES_CHKSUM:class-nativesdk += "${LIC_FILES_CHKSUM_HOST}"
