#!/bin/sh
#
# SPDX-License-Identifier: MIT
#

set -e

PSEUDO_UNLOAD=1 ${binprefix}qemuwrapper -L $D $D${libexecdir}/${binprefix}gio-querymodules $D${libdir}/gio/modules/

[ ! -e $D${libdir}/gio/modules/giomodule.cache ] ||
	chown root:root $D${libdir}/gio/modules/giomodule.cache
