DESCRIPTION = "A low-level debug tool for communicating with devices attached to an MDIO bus"
SECTION = "networking"
HOMEPAGE = "https://github.com/wkz/mdio-tools"
LICENSE = "GPL-2.0-or-later"
LIC_FILES_CHKSUM = "file://${WORKDIR}/git/COPYING;md5=b234ee4d69f5fce4486a80fdaf4a4263"

SRC_URI = "git://github.com/wkz/mdio-tools.git;protocol=https;branch=master"
SRCREV = "f74eaf38dbda441df4fcaeb21ca4465957953a2f"
