#!/bin/sh
### BEGIN INIT INFO
# Provides:          oprofile-server
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OProfileUI server
# Description:       
### END INIT INFO

. /etc/init.d/functions

case "$1" in
  start)
        echo "Starting OProfileUI server"
	. /etc/profile
	/usr/bin/oprofile-server &
  ;;

  stop)
        echo "Stopping OProfileUI server"
        killproc oprofile-server
  ;;

  restart)
	$0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
