KEY_SIGN ?= "openssl"

KEY_BB_INDEX ?= "1"
KEY_BL31_INDEX ?= "1"
KEY_OPTEE_INDEX ?= "1"
KEY_UBOOT_INDEX ?= "1"

KEY_BB_ID ?= "11"
KEY_BL31_ID ?= "11"
KEY_OPTEE_ID ?= "11"
KEY_UBOOT_ID ?= "11"

KEY_BB ?= "/home/tim/keys/openssl/skmt_ecc_key_1.der"
KEY_BL31 ?= "/home/tim/keys/openssl/skmt_ecc_key_1.der"
KEY_OPTEE ?= "/home/tim/keys/openssl/skmt_ecc_key_1.der"
KEY_UBOOT ?= "/home/tim/keys/openssl/skmt_ecc_key_1.der"

SKMT_BIN ?= "/home/tim/keys/openssl/Kmt_TipFwL0_Skmt_TipFwL1.bin"
