# List of known non-reproducible package of the meta-initramfs layer
# Please keep this list sorted
KNOWN_NON_REPRO_META_INITRAMFS = " \
    kexecboot-klibc \
    kexecboot-klibc-dbg \
    kexec-klibc \
    kexec-tools-klibc-dbg \
    mtdinfo-klibc \
    ubiattach-klibc \
    ubiblock-klibc \
    ubicrc32-klibc \
    ubidetach-klibc \
    ubiformat-klibc \
    ubimkvol-klibc \
    ubinfo-klibc \
    ubinize-klibc \
    ubirename-klibc \
    ubirmvol-klibc \
    ubirsvol-klibc \
    ubiupdatevol-klibc \
    ubi-utils-klibc-dbg \
    vmcore-dmesg-klibc \
"
