# meta-securiyt Maintainers File
#
# This file contains a list of recipe maintainers.
#
# Please submit any patches against recipes in meta to the 
# Yocto mail list (yocto@yoctoproject.org)
#
# If you have problems with or questions about a particular recipe, feel
# free to contact the maintainer directly (cc:ing the appropriate mailing list
# puts it in the archive and helps other people who might have the same
# questions in the future), but please try to do the following first:
#
#  - look in the Yocto Project Bugzilla
#    (http://bugzilla.yoctoproject.org/) to see if a problem has
#    already been reported
#
# The format is as a bitbake variable override for each recipe
#
#	RECIPE_MAINTAINER_pn-<recipe name> = "Full Name <address@domain>"
#
# Please keep this list in alphabetical order.
RECIPE_MAINTAINER_pn-aircrack-ng = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-apparmor = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-bastille = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-buck-security = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-ccs-tools = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-checksec = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-checksecurity = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-clamav = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-ding-libs = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-ecryptfs-utils = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-fscryptctl = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-google-authenticator-libpam = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-hash-perl = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-isic = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-keyutils = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-libaes-siv = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-libgssglue = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-libhtp = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-libmhash = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-libmspack = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-lib-perl = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-libseccomp = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-libwhisker2-perl = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-ncrack = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-nikto = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-paxctl = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-python3-fail2ban = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-python3-scapy = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-python-fail2ban = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-python-scapy = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-redhat-security = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-samhain = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-smack = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-sssd = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-suricata = "Armin Kuster <akuster808@gmail.com>"
RECIPE_MAINTAINER_pn-tripwire = "Armin Kuster <akuster808@gmail.com>"
