#!/bin/bash

VENTURA2_EVT_SKU1_CONF_PATH="/usr/share/phosphor-virtual-sensor/ventura2_evt_sku1.json"
VENTURA2_EVT_SKU2_CONF_PATH="/usr/share/phosphor-virtual-sensor/ventura2_evt_sku2.json"
VENTURA2_PVT_SKU1_CONF_PATH="/usr/share/phosphor-virtual-sensor/ventura2_pvt_sku1.json"
VENTURA2_PVT_SKU1C_CONF_PATH="/usr/share/phosphor-virtual-sensor/ventura2_pvt_sku1c.json"
VENTURA2_PVT_SKU4_CONF_PATH="/usr/share/phosphor-virtual-sensor/ventura2_pvt_sku4.json"
VENTURA2_PVT_SKU4C_CONF_PATH="/usr/share/phosphor-virtual-sensor/ventura2_pvt_sku4c.json"
CONFIG_DIR="/var/lib/phosphor-virtual-sensor"
CONFIG_PATH="$CONFIG_DIR/virtual_sensor_config.json"

check_ventura2_sku()
{
    fru_path=$(busctl tree xyz.openbmc_project.FruDevice \
        | grep Ventura2_RMC | awk '{print $2}')

    if [ -z "$fru_path" ]; then
        echo "Ventura2_RMC FRU not found"
        return 1
    fi

    sku=$(busctl get-property xyz.openbmc_project.FruDevice \
            "$fru_path" xyz.openbmc_project.FruDevice PRODUCT_INFO_AM1 \
        2>/dev/null | awk -F\" '{print $2}')
    echo "$sku"
}

check_ventura2_stage()
{
    fru_path=$(busctl tree xyz.openbmc_project.FruDevice | grep Ventura2_RMC | awk '{print $2}')

    if [ -z "$fru_path" ]; then
        echo "Ventura2_RMC FRU not found"
        return 1
    fi

    stage=${fru_path##*_}
    echo "$stage"
}

# create config folder if not exist
if [ ! -d "$CONFIG_DIR" ]; then
    mkdir -p "$CONFIG_DIR"
fi

# clean up exist link
if [ -L "$CONFIG_PATH" ]; then
    rm "$CONFIG_PATH"
fi

# check interposer board type
for i in {1..10}
do
    echo "check interposer board type, attempt $i"
    sku=$(check_ventura2_sku | tr '[:upper:]' '[:lower:]')
    stage=$(check_ventura2_stage | tr '[:upper:]' '[:lower:]')
    echo "Stage: $stage, SKU: $sku"
    case "$stage" in
        "evt")
            case "$sku" in
                "sku 1" | "sku 4")
                    echo "Applying virtual sensor configuration: $(basename "$VENTURA2_EVT_SKU1_CONF_PATH")"
                    ln -sf "$VENTURA2_EVT_SKU1_CONF_PATH" "$CONFIG_PATH"
                    break ;;
                "sku 2" | "sku 1c" | "sku 4c")
                    echo "Applying virtual sensor configuration: $(basename "$VENTURA2_EVT_SKU2_CONF_PATH")"
                    ln -sf "$VENTURA2_EVT_SKU2_CONF_PATH" "$CONFIG_PATH"
                    break ;;
                *)
                    echo "Unknown SKU for EVT: $sku"
                    ;;
            esac
            ;;
        "pvt")
            case "$sku" in
                "sku 1")
                    echo "Applying virtual sensor configuration: $(basename "$VENTURA2_PVT_SKU1_CONF_PATH")"
                    ln -sf "$VENTURA2_PVT_SKU1_CONF_PATH" "$CONFIG_PATH"
                    break ;;
                "sku 1c")
                    echo "Applying virtual sensor configuration: $(basename "$VENTURA2_PVT_SKU1C_CONF_PATH")"
                    ln -sf "$VENTURA2_PVT_SKU1C_CONF_PATH" "$CONFIG_PATH"
                    break ;;
                "sku 4")
                    echo "Applying virtual sensor configuration: $(basename "$VENTURA2_PVT_SKU4_CONF_PATH")"
                    ln -sf "$VENTURA2_PVT_SKU4_CONF_PATH" "$CONFIG_PATH"
                    break ;;
                "sku 4c")
                    echo "Applying virtual sensor configuration: $(basename "$VENTURA2_PVT_SKU4C_CONF_PATH")"
                    ln -sf "$VENTURA2_PVT_SKU4C_CONF_PATH" "$CONFIG_PATH"
                    break ;;
                "sku 2")
                    echo "Applying virtual sensor configuration: $(basename "$VENTURA2_EVT_SKU2_CONF_PATH")"
                    ln -sf "$VENTURA2_EVT_SKU2_CONF_PATH" "$CONFIG_PATH"
                    break ;;
                *)
                    echo "Unknown SKU for PVT: $sku"
                    ;;
            esac
            ;;

        *)
            echo "Unknown stage detected: $stage"
            ;;
    esac
    sleep 1
done
