# Kernel always panic immediately upon any OOM condition
vm.panic_on_oom=2

# Limits dirty pages to 5% of system memory.
vm.dirty_ratio=5

# Start writeback once once 2% dirty pages reached
vm.dirty_background_ratio=2

# How often kernel's flusher threads wake up (10 sec)
vm.dirty_expire_centisecs=1000

# Reserve 16 MB so that system starts reclaiming.
vm.min_free_kbytes=16384
