EXTRA_OECMAKE:prepend = " \
    -DENABLE_LIB_ONLY=ON \
    -DENABLE_STATIC_LIB=ON \
    -DENABLE_SHARED_LIB=OFF \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
    -DENABLE_SHARED_LIB=OFF \
    -DENABLE_HTTP3=OFF \
    -DWITH_LIBXML2=OFF \
    -DWITH_JEMALLOC=OFF \
    -DWITH_MRUBY=OFF \
    -DWITH_NEVERBLEED=OFF \
    -DWITH_LIBBPF=OFF \
    -DENABLE_ASIO_LIB=OFF \
    -DENABLE_THREADS=OFF \
"
