SUMMARY = "Pyiface is a package that exposes the network interfaces of the operating system in a easy to use and transparent way"
SECTION = "devel/python"
HOMEPAGE = "https://pypi.python.org/pypi/pyiface/"
LICENSE = "GPLv3+"

LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=4fe869ee987a340198fb0d54c55c47f1"

SRC_URI[md5sum] = "06c3c71fe51df740dae6a88a13afb5e0"
SRC_URI[sha256sum] = "4bb79100cbcf7344a1ccaddc578cd6455da47d8eac6eb1bf903ec32e043af924"

inherit pypi
