SUMMARY = "comprehensive password hashing framework supporting over 30 schemes"
DESCRIPTION = "\
Passlib is a password hashing library for Python 2 & 3, which provides cross-platform \
implementations of over 30 password hashing algorithms, as well as a framework for \
managing existing password hashes. It’s designed to be useful for a wide range of \
tasks, from verifying a hash found in /etc/shadow, to providing full-strength password \
hashing for multi-user applications."
HOMEPAGE = "https://bitbucket.org/ecollins/passlib"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://LICENSE;md5=bae8faa3e2689ee0df3f2127fc4517f5"
PR = "r0"

SRC_URI[md5sum] = "d2edd6c42cde136a538b48d90a06ad67"
SRC_URI[sha256sum] = "a83d34f53dc9b17aa42c9a35c3fbcc5120f3fcb07f7f8721ec45e6a27be347fc"
