SUMMARY = "Python expectaton library"
DESCRIPTION = "Minimal but very flexible implementation of the expect pattern"
SECTION = "devel/python"
HOMEPAGE = " https://bitbucket.org/dwt/pyexpect"
LICENSE = "ISC"
LIC_FILES_CHKSUM = "file://README.md;md5=500b884e9dcd5f677a53cbbee8ace939"

inherit pypi

SRC_URI[md5sum] = "c71307d6c7096fdbde0813018dfa0092"
SRC_URI[sha256sum] = "d656ef7e07a8aa539ce0a4883a683341037b6fc1c329bf55b63bffbf2cce9582"
