SUMMARY = "MQTT version 3.1/3.1.1 client library"
LICENSE = "EPL-1.0 | EDL-1.0"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=eb48c6ee2cb9f5b8b9fe75e6f817bdfc \
                    file://epl-v10;md5=8d383c379e91d20ba18a52c3e7d3a979 \
                    file://edl-v10;md5=c09f121939f063aeb5235972be8c722c \
"
SRCNAME = "paho-mqtt"

inherit pypi
SRC_URI[md5sum] = "b9338236e2836e8579ef140956189cc4"
SRC_URI[sha256sum] = "2c9ef5494cfc1e41a9fff6544c5a2cd59ea5d401d9119a06ecf7fad6a2ffeb93"

DEPENDS += "${PYTHON_PN}-pytest-runner-native"

RDEPENDS_${PN} = "\
               ${PYTHON_PN}-math \
               ${PYTHON_PN}-io \
               ${PYTHON_PN}-threading \
"
