SUMMARY = "Linux network configuration library for Python"
DESCRIPTION = "This library contains Python bindings to ioctl calls"
SECTION = "devel/python"
HOMEPAGE = "http://github.com/rlisagor/pynetlinux"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=74e1861736ee959824fe7542323c12e9"

inherit pypi

SRC_URI[md5sum] = "3336e5d4a478acca4e35bf3125b4f883"
SRC_URI[sha256sum] = "4ad08298c9f5ba15a11cddc639ba8778cabdfc402b51066d9e0a325e5a5b391c"
