#!/bin/sh
cd tests
{ ./runtests.pl -a -n -s || echo "FAIL: curl" ; } | sed \
     -e 's|\([^ ]* *\) \([^ ]* *\)...OK|PASS: \1 \2|' \
     -e 's|\([^ ]* *\) \([^ ]* *\)...FAILED|FAIL: \1 \2|' \
     -e 's/Warning: test[0-9]\+ not present in tests\/data\/Makefile.inc//'
