#!/bin/sh

cd @PTEST_PATH@
keynote verify -e testsuite/test-env \
               -r false,maybe,probably,true \
               -k testsuite/auth1 -k testsuite/auth2 \
               -k testsuite/auth3 -k testsuite/auth4 \
               -l testsuite/test-assertion1 \
               -l testsuite/test-assertion2 \
               -l testsuite/test-assertion3 \
               -l testsuite/test-assertion4 \
               -l testsuite/test-assertion5 \
               -l testsuite/test-assertion6 \
               -l testsuite/test-assertion7 \
               && echo "PASS: keynote-ptest" \
               || echo "FAIL: keynote-ptest"
