OBMC_IMAGE_EXTRA_INSTALL_append_kudo = " ipmitool"
OBMC_IMAGE_EXTRA_INSTALL_append_kudo = " ethtool"
OBMC_IMAGE_EXTRA_INSTALL_append_kudo = " google-ipmi-sys"
OBMC_IMAGE_EXTRA_INSTALL_append_kudo = " google-ipmi-i2c"
OBMC_IMAGE_EXTRA_INSTALL_append_kudo = " phosphor-ipmi-blobs"
OBMC_IMAGE_EXTRA_INSTALL_append_kudo = " phosphor-ipmi-ethstats"
OBMC_IMAGE_EXTRA_INSTALL_append_kudo = " phosphor-ipmi-flash"
