#!/bin/bash -e
# shellcheck source=meta-facebook/meta-minerva/recipes-minerva/plat-tool/files/minerva-common-functions
source /usr/libexec/minerva-common-functions

power_on_led_init() {
    systemctl start obmc-led-group-start@power_on.service
}

# set initial value for GPIO output pins
set_gpio PWREN_MTIA_BLADE0_EN_N 0
set_gpio PWREN_MTIA_BLADE1_EN_N 0
set_gpio PWREN_MTIA_BLADE2_EN_N 0
set_gpio PWREN_MTIA_BLADE3_EN_N 0
set_gpio PWREN_MTIA_BLADE4_EN_N 0
set_gpio PWREN_MTIA_BLADE5_EN_N 0
set_gpio PWREN_MTIA_BLADE6_EN_N 0
set_gpio PWREN_MTIA_BLADE7_EN_N 0
set_gpio PWREN_MTIA_BLADE8_EN_N 0
set_gpio PWREN_MTIA_BLADE9_EN_N 0
set_gpio PWREN_MTIA_BLADE10_EN_N 0
set_gpio PWREN_MTIA_BLADE11_EN_N 0
set_gpio PWREN_MTIA_BLADE12_EN_N 0
set_gpio PWREN_MTIA_BLADE13_EN_N 0
set_gpio PWREN_MTIA_BLADE14_EN_N 0
set_gpio PWREN_MTIA_BLADE15_EN_N 0

set_gpio PWREN_NW_BLADE0_EN_N 0
set_gpio PWREN_NW_BLADE1_EN_N 0
set_gpio PWREN_NW_BLADE2_EN_N 0
set_gpio PWREN_NW_BLADE3_EN_N 0
set_gpio PWREN_NW_BLADE4_EN_N 0
set_gpio PWREN_NW_BLADE5_EN_N 0

set_gpio PWREN_MTIA_BLADE0_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE1_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE2_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE3_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE4_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE5_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE6_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE7_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE8_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE9_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE10_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE11_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE12_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE13_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE14_HSC_EN_N 0
set_gpio PWREN_MTIA_BLADE15_HSC_EN_N 0

set_gpio PWREN_NW_BLADE0_HSC_EN_N 0
set_gpio PWREN_NW_BLADE1_HSC_EN_N 0
set_gpio PWREN_NW_BLADE2_HSC_EN_N 0
set_gpio PWREN_NW_BLADE3_HSC_EN_N 0
set_gpio PWREN_NW_BLADE4_HSC_EN_N 0
set_gpio PWREN_NW_BLADE5_HSC_EN_N 0

set_gpio PWREN_FCB_TOP_0_EN_N 0
set_gpio PWREN_FCB_TOP_1_EN_N 0
set_gpio PWREN_FCB_MIDDLE_0_EN_N 0
set_gpio PWREN_FCB_MIDDLE_1_EN_N 0
set_gpio PWREN_FCB_BOTTOM_1_EN_N 0
set_gpio PWREN_FCB_BOTTOM_0_EN_N 0

set_gpio FM_CMM_AC_CYCLE_N 1

set_gpio RST_I2CRST_FCB_BOTTOM_1_N 1
set_gpio RST_I2CRST_FCB_BOTTOM_0_N 1
set_gpio RST_I2CRST_FCB_MIDDLE_0_N 1
set_gpio RST_I2CRST_FCB_MIDDLE_1_N 1
set_gpio RST_I2CRST_FCB_TOP_0_N 1
set_gpio RST_I2CRST_FCB_TOP_1_N 1

set_gpio FM_MDIO_SW_SEL 0
set_gpio FM_88E6393X_BIN_UPDATE_EN_N 1
set_gpio WATER_VALVE_CLOSED_N 1
set_gpio BMC_READY 1

power_on_led_init

exit 0
