Upstream-Status: Inappropriate [configuration]

diff -ruN lrzsz-0.12.20_org/src/Makefile.in lrzsz-0.12.20_patch/src/Makefile.in
--- lrzsz-0.12.20_org/src/Makefile.in	1998-12-30 17:31:46.000000000 +0100
+++ lrzsz-0.12.20_patch/src/Makefile.in	2004-04-29 13:57:33.434909656 +0200
@@ -372,13 +372,13 @@
 	rm -f $(DESTDIR)/$(bindir)/`echo lsb | sed -e '$(transform)'`
 	ln $(DESTDIR)/$(bindir)/`echo lsz |sed -e '$(transform)'` \
 		$(DESTDIR)/$(bindir)/`echo lsb |sed -e '$(transform)'` 
-	rm -f $(bindir)/`echo lsx | sed -e '$(transform)'`
+	rm -f $(DESTDIR)/$(bindir)/`echo lsx | sed -e '$(transform)'`
 	ln $(DESTDIR)/$(bindir)/`echo lsz |sed -e '$(transform)'` \
 		$(DESTDIR)/$(bindir)/`echo lsx |sed -e '$(transform)'` 
-	rm -f $(bindir)/`echo lrb | sed -e '$(transform)'`
+	rm -f $(DESTDIR)/$(bindir)/`echo lrb | sed -e '$(transform)'`
 	ln $(DESTDIR)/$(bindir)/`echo lrz |sed -e '$(transform)'` \
 		$(DESTDIR)/$(bindir)/`echo lrb |sed -e '$(transform)'` 
-	rm -f $(bindir)/`echo lrx | sed -e '$(transform)'`
+	rm -f $(DESTDIR)/$(bindir)/`echo lrx | sed -e '$(transform)'`
 	ln $(DESTDIR)/$(bindir)/`echo lrz |sed -e '$(transform)'` \
 		$(DESTDIR)/$(bindir)/`echo lrx |sed -e '$(transform)'` 
 #	rm -f $(bindir)/`echo lrzszbug | sed -e '$(transform)'`
