EKB_BRANCH = "main-p10"
EKB_URI = "git://git@github.com/open-power/pub-ekb;branch=${EKB_BRANCH};protocol=https"
EKB_REV = "79f40fbad5c15d41347a739cd3bcb9ff66e5bac9"

REQ_ATTRS_XMLS = "hwpf/fapi2/xml/attribute_info/chip_attributes.xml \
           hwpf/fapi2/xml/attribute_info/common_attributes.xml \
           hwpf/fapi2/xml/attribute_info/scratch_attributes.xml \
           hwpf/fapi2/xml/attribute_info/system_attributes.xml \
           hwpf/fapi2/xml/attribute_info/unit_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_bars_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_chip_ec_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_clock_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_freq_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_hcode_image_build_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_ipl_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_ipl_customize_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_memory_bars_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_nest_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_pervasive_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_qme_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_runn_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_sbe_load_bootloader_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_sbe_attributes.xml"
