#!/bin/bash

# shellcheck source=meta-facebook/meta-sanmiguel/recipes-phosphor/state/phosphor-state-manager/power-cmd
source /usr/libexec/phosphor-state-manager/power-cmd

host_graceful_power_off
exit 0
