#!/bin/bash

# shellcheck source=meta-facebook/meta-sanmiguel/recipes-phosphor/state/phosphor-state-manager/power-cmd
source /usr/libexec/phosphor-state-manager/power-cmd

host_power_on
ret=$?

if [ $ret -ne 0 ]; then
    log_msg="host power on failed"
    echo "$log_msg"
    exit 1
fi

systemctl start obmc-led-group-start@power_on.service
exit 0
