#!/bin/sh

testbins="gpiod-test gpio-tools-test gpiod-cxx-test gpiod_py_test.py"

ptestdir=$(dirname "$(readlink -f "$0")")
cd $ptestdir/tests

for testbin in $testbins; do
	if test -e ./$testbin; then
		./$testbin > ./$testbin.out 2>&1
		if [ $? -ne 0 ]; then
			echo "FAIL: $testbin"
		else
			echo "PASS: $testbin"
		fi
	else
		echo "SKIP: $testbin"
	fi
done
