#! /bin/sh

set -eux
if id -u glib2-test; then
   userdel glib2-test
fi
useradd glib2-test
cd /tmp
su glib2-test -c 'G_TEST_TMPDIR=`readlink -f /tmp` gnome-desktop-testing-runner glib'
userdel glib2-test
