#!/bin/bash

busctl set-property \
xyz.openbmc_project.State.Chassis"$1" \
/xyz/openbmc_project/state/chassis"$1" \
xyz.openbmc_project.State.Chassis \
CurrentPowerState s \
xyz.openbmc_project.State.Chassis.PowerState.On

exit 0
