#!/bin/bash

# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions
# shellcheck source=meta-facebook/meta-santabarbara/recipes-phosphor/state/phosphor-state-manager/power-cmd
source /usr/libexec/phosphor-state-manager/power-cmd


currentstate=$(busctl get-property \
    xyz.openbmc_project.State.Host0 \
    /xyz/openbmc_project/state/host0 \
    xyz.openbmc_project.State.Host \
    CurrentHostState | awk '{print $2}' | tr -d '"')

if [ "$currentstate" == "xyz.openbmc_project.State.Host.HostState.TransitioningToRunning" ]; then
    exit 0
fi

if is_service_busy host-poweron@0.service; then
    exit 0
fi

if is_service_busy host-powerreset@0.service; then
    exit 0
fi

# Sync power status to "On" for abnormal power-on scenarios.
if [ "$(power_status)" == "on" ]; then
    transition=$(busctl get-property \
        xyz.openbmc_project.State.Host0 \
        /xyz/openbmc_project/state/host0 \
        xyz.openbmc_project.State.Host \
        RequestedHostTransition | awk '{print $2}' | tr -d '"')
    if [ "$transition" != "xyz.openbmc_project.State.Host.Transition.On" ]; then
        busctl set-property xyz.openbmc_project.State.Host0 \
            /xyz/openbmc_project/state/host0 \
            xyz.openbmc_project.State.Host \
            RequestedHostTransition s \
            xyz.openbmc_project.State.Host.Transition.On
    elif [ "$currentstate" == "xyz.openbmc_project.State.Host.HostState.TransitioningToOff" ]; then
        busctl set-property xyz.openbmc_project.State.Host0 \
            /xyz/openbmc_project/state/host0 \
            xyz.openbmc_project.State.Host \
            CurrentHostState s xyz.openbmc_project.State.Host.HostState.Off
        sleep 0.1
        busctl set-property xyz.openbmc_project.State.Host0 \
            /xyz/openbmc_project/state/host0 \
            xyz.openbmc_project.State.Host \
            CurrentHostState s xyz.openbmc_project.State.Host.HostState.Running
    fi
fi

exit 0
