local-tty = /dev/ttyUSBdevice21
baud = 57600
console-id = rainbow2_MEDHA0_CRM
logfile = /var/log/obmc-console-rainbow2_MEDHA0_CRM.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow2_MEDHA0_CRM-timestamped.log
