local-tty = /dev/ttyUSBdevice34
baud = 57600
console-id = rainbow1_MEDHA0_UART2
logfile = /var/log/obmc-console-rainbow1_MEDHA0_UART2.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow1_MEDHA0_UART2-timestamped.log
