local-tty = /dev/ttyUSBdevice46
baud = 57600
console-id = rainbow3_MEDHA0_UART0
logfile = /run/log/obmc-console-rainbow3_MEDHA0_UART0.log
log-timestamp = 1
logfile-timestamped = /run/log/obmc-console-rainbow3_MEDHA0_UART0-timestamped.log
