local-tty = /dev/ttyUSBdevice44
baud = 57600
console-id = rainbow3_HAMSA_UART2
logfile = /run/log/obmc-console-rainbow3_HAMSA_UART2.log
log-timestamp = 1
logfile-timestamped = /run/log/obmc-console-rainbow3_HAMSA_UART2-timestamped.log
