local-tty = /dev/ttyUSBdevice60
baud = 115200
console-id = swb_switch
logfile = /var/log/obmc-console-swb_switch.log
logfile-timestamped = /var/log/obmc-console-swb_switch-timestamped.log
log-timestamp = 1
