local-tty = /dev/ttyUSBdevice15
baud = 57600
console-id = rainbow2_HAMSA_UART1
logfile = /var/log/obmc-console-rainbow2_HAMSA_UART1.log
logfile-timestamped = /var/log/obmc-console-rainbow2_HAMSA_UART1-timestamped.log
log-timestamp = 1
