local-tty = /dev/ttyUSBdevice30
baud = 57600
console-id = rainbow1_HAMSA_UART2
logfile = /run/log/obmc-console-rainbow1_HAMSA_UART2.log
log-timestamp = 1
logfile-timestamped = /run/log/obmc-console-rainbow1_HAMSA_UART2-timestamped.log
