local-tty = /dev/ttyUSBdevice0
baud = 57600
console-id = rainbow0_HAMSA_UART0
logfile = /run/log/obmc-console-rainbow0_HAMSA_UART0.log
logfile-timestamped = /run/log/obmc-console-rainbow0_HAMSA_UART0-timestamped.log
log-timestamp = 1
