local-tty = /dev/ttyUSBdevice18
baud = 57600
console-id = rainbow2_MEDHA0_UART0
logfile = /var/log/obmc-console-rainbow2_MEDHA0_UART0.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow2_MEDHA0_UART0-timestamped.log
