local-tty = /dev/ttyUSBdevice54
baud = 57600
console-id = rainbow3_OWL_E_UART
logfile = /var/log/obmc-console-rainbow3_OWL_E_UART.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow3_OWL_E_UART-timestamped.log
