local-tty = /dev/ttyUSBdevice49
baud = 57600
console-id = rainbow3_MEDHA0_CRM
logfile = /var/log/obmc-console-rainbow3_MEDHA0_CRM.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow3_MEDHA0_CRM-timestamped.log
