local-tty = /dev/ttyUSBdevice36
baud = 57600
console-id = rainbow1_MEDHA1_UART0
logfile = /var/log/obmc-console-rainbow1_MEDHA1_UART0.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow1_MEDHA1_UART0-timestamped.log
