local-tty = /dev/ttyUSBdevice35
baud = 57600
console-id = rainbow1_MEDHA0_CRM
logfile = /var/log/obmc-console-rainbow1_MEDHA0_CRM.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow1_MEDHA0_CRM-timestamped.log
