local-tty = /dev/ttyUSBdevice40
baud = 57600
console-id = rainbow1_OWL_E_UART
logfile = /run/log/obmc-console-rainbow1_OWL_E_UART.log
logsize = 64k
log-timestamp = 1
logfile-timestamped = /run/log/obmc-console-rainbow1_OWL_E_UART-timestamped.log
