local-tty = /dev/ttyUSBdevice28
baud = 57600
console-id = rainbow1_HAMSA_UART0
logfile = /run/log/obmc-console-rainbow1_HAMSA_UART0.log
log-timestamp = 1
logfile-timestamped = /run/log/obmc-console-rainbow1_HAMSA_UART0-timestamped.log
