local-tty = /dev/ttyUSBdevice57
baud = 57600
console-id = rainbow2_mmc
logfile = /var/log/obmc-console-rainbow2_mmc.log
logfile-timestamped = /var/log/obmc-console-rainbow2_mmc-timestamped.log
log-timestamp = 1
