local-tty = /dev/ttyUSBdevice45
baud = 57600
console-id = rainbow3_HAMSA_CRM
logfile = /var/log/obmc-console-rainbow3_HAMSA_CRM.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow3_HAMSA_CRM-timestamped.log
logsize = 256k
