local-tty = /dev/ttyUSBdevice41
baud = 57600
console-id = rainbow1_OWL_W_UART
logfile = /var/log/obmc-console-rainbow1_OWL_W_UART.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow1_OWL_W_UART-timestamped.log
