local-tty = /dev/ttyUSBdevice37
baud = 57600
console-id = rainbow1_MEDHA1_UART1
logfile = /var/log/obmc-console-rainbow1_MEDHA1_UART1.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow1_MEDHA1_UART1-timestamped.log
