local-tty = /dev/ttyUSBdevice49
baud = 57600
console-id = rainbow3_MEDHA0_CRM
logfile = /run/log/obmc-console-rainbow3_MEDHA0_CRM.log
logsize = 64k
log-timestamp = 1
logfile-timestamped = /run/log/obmc-console-rainbow3_MEDHA0_CRM-timestamped.log
