local-tty = /dev/ttyUSBdevice25
baud = 57600
console-id = rainbow2_MEDHA1_CRM
logfile = /var/log/obmc-console-rainbow2_MEDHA1_CRM.log
log-timestamp = 1
logfile-timestamped = /var/log/obmc-console-rainbow2_MEDHA1_CRM-timestamped.log
