local-tty = /dev/ttyUSBdevice25
baud = 57600
console-id = rainbow2_MEDHA1_CRM
logfile = /run/log/obmc-console-rainbow2_MEDHA1_CRM.log
logsize = 64k
log-timestamp = 1
logfile-timestamped = /run/log/obmc-console-rainbow2_MEDHA1_CRM-timestamped.log
