local-tty = /dev/ttyUSBdevice16
baud = 57600
console-id = rainbow2_HAMSA_UART2
logfile = /run/log/obmc-console-rainbow2_HAMSA_UART2.log
log-timestamp = 1
logfile-timestamped = /run/log/obmc-console-rainbow2_HAMSA_UART2-timestamped.log
