local-tty = /dev/ttyUSBdevice58
baud = 57600
console-id = rainbow1_mmc
logfile = /var/log/obmc-console-rainbow1_mmc.log
logfile-timestamped = /var/log/obmc-console-rainbow1_mmc-timestamped.log
log-timestamp = 1
