local-tty = /dev/ttyUSBdevice56
baud = 57600
console-id = rainbow0_mmc
logfile = /run/log/obmc-console-rainbow0_mmc.log
logfile-timestamped = /run/log/obmc-console-rainbow0_mmc-timestamped.log
log-timestamp = 1
