#!/bin/bash
# shellcheck source=meta-facebook/meta-yosemite4/recipes-yosemite4/plat-tool/files/yosemite4-common-functions
source /usr/libexec/yosemite4-common-functions
echo "Start rescan-fru-ocp-setting"
# We observed that the rescan service would be execute during BMC
# boot up, and the entity-manager might remove and add inventories
# again. It caused pldmd fail to get inventories sometimes.
# Therefore, we temporary add bmc-ready check before we clarify the
# and fix entity-manager unexpected behavior.
bmc_ready=$(busctl get-property xyz.openbmc_project.State.BMC /xyz/openbmc_project/state/bmc0 xyz.openbmc_project.State.BMC CurrentBMCState | awk '{print $2}' | tr -d '"')
if [ "$bmc_ready" != "xyz.openbmc_project.State.BMC.BMCState.Ready" ]; then
    echo "BMC is not ready, exiting..."
    set_hsc_ocp_values
    exit 0
fi

sleep 2
bus=$(($1 + 15))
echo "Start rescan slot $1 fru bus $bus."
# rescan eeprom for fru information
busctl call xyz.openbmc_project.FruDevice /xyz/openbmc_project/FruDevice xyz.openbmc_project.FruDeviceManager ReScanBus q $bus --timeout=120
echo "End rescan slot $1 fru bus $bus for fru removal."
# wait for fru device to be ready
sleep 10
set_hsc_ocp_values
echo "End slot $1 rescan-fru-ocp-setting"
