EXTRA_OECMAKE += "-DBMCWEB_ENABLE_REDFISH_CPU_LOG=ON \
                  -DBMCWEB_ENABLE_REDFISH_RAW_PECI=ON \
                  -DBMCWEB_ENABLE_REDFISH_BMC_JOURNAL=ON \
                  -DBMCWEB_ENABLE_DBUS_REST=OFF"

