#!/bin/bash
# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions

GPIO_LOW=0

#======================================
# output pins
#======================================
out_rmc_large_leak_n="LEAK_DETECT_RMC_N"

set_request_host_transition()
{
    busctl set-property xyz.openbmc_project.State.Host0 \
        /xyz/openbmc_project/state/host0 \
        xyz.openbmc_project.State.Host \
        RequestedHostTransition s "$1"
}

set_gpio "$out_rmc_large_leak_n" "$GPIO_LOW"

set_request_host_transition "xyz.openbmc_project.State.Host.Transition.Off"

exit 0