#!/bin/bash

mapper wait /xyz/openbmc_project/state/chassis0
mapper wait /xyz/openbmc_project/state/chassis1

busctl set-property xyz.openbmc_project.State.Chassis0 \
    /xyz/openbmc_project/state/chassis0 \
    xyz.openbmc_project.State.Chassis \
    CurrentPowerState s \
    xyz.openbmc_project.State.Chassis.PowerState.On

busctl set-property xyz.openbmc_project.State.Chassis1 \
    /xyz/openbmc_project/state/chassis1 \
    xyz.openbmc_project.State.Chassis \
    CurrentPowerState s \
    xyz.openbmc_project.State.Chassis.PowerState.On

exit 0
