#!/bin/bash

# shellcheck source=meta-facebook/meta-rainiera7/recipes-phosphor/state/phosphor-state-manager/power-cmd
source /usr/libexec/phosphor-state-manager/power-cmd

# reset
echo "Starting reset"

power_reset
