#!/bin/sh

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 partition-name version-id" >&2
  exit 1
fi

# Get the pnor mtd device number
pnor=`grep pnor /proc/mtd |cut -c 4`

# Create mount dir if it does not exist
mountdir="/media/$1"
if [ ! -d $mountdir ]
then
  mkdir $mountdir
fi

# Create a static ubi volume of arbitrary size 32MB if it does not exist, the
# volume will shrink to fit the pnor image if smaller
pnordev="/dev/ubi$pnor"
vol=`ubinfo -d $pnor -a | grep $1`
if [ -z "$vol" ]
then
  ubimkvol $pnordev -N $1 -s 32MiB --type=static
fi

# Get the volume id assigned by the uibmkvol call above. Example ubinfo output
# from which the id "0" needs to be parsed out: "Volume ID:   0 (on ubi7)"
volumeid=`ubinfo -d $pnor -N $1 | grep "Volume ID" | sed -e "s|Volume ID:||" -e "s/^ *//" | grep -o "^\S*"`

# Create a ubi block if it does not exist, this is needed for read-only volumes,
# and update the volume with the pnor squashfs image
block="/dev/ubiblock${pnor}_${volumeid}"
if [ ! -e $block ]
then
  pnordevid="${pnordev}_${volumeid}"
  ubiblock --create $pnordevid
  ubiupdatevol $pnordevid /tmp/images/$2/pnor.xz.squashfs
fi

# Mount the volume if it is not mounted already
if ! grep -q $1 /proc/mounts
then
  mount -t squashfs -o ro $block $mountdir
fi
