#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 partition-name" >&2
  exit 1
fi

# Get the pnor mtd device number
pnor=`grep pnor /proc/mtd |cut -c 4`

# Create mount dir if it does not exist
mountdir="/media/$1"
if [ ! -d $mountdir ]
then
  mkdir $mountdir
fi

# Create a dynamic ubi volume of initial arbitrary size 1MB if it does not
# exist already, the volume will grow dynamically as needed
vol=`ubinfo -d $pnor -a | grep $1`
if [ -z "$vol" ]
then
  ubimkvol /dev/ubi$pnor -N $1 -s 1MiB
fi

# Mount the volume if it is not mounted already
if ! grep -q $1 /proc/mounts
then
  mount -t ubifs ubi$pnor:$1 $mountdir
fi
