#!/bin/bash

# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions

is_host_present() {
    local COMe_PRSNT="/xyz/openbmc_project/inventory/system/board/Ventura2_SCM/PRSNT_COMe"
    if mapper get-service "$COMe_PRSNT" > /dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

# Power Good Status
power_status() {
    if [ "$(get_gpio "R_PWRGD_PCH_PWROK")" -eq 1 ] ; then
        echo "on"
    else
        echo "off"
    fi
}

# Force DC off
force_power_off() {
    if ! is_host_present; then
        echo "Host not present, skip force off."
        return 0
    fi
    if [ "$(power_status)" == "on" ]; then
        set_gpio SYS_BMC_PWRBTN_R_N 0
        sleep 5
        set_gpio SYS_BMC_PWRBTN_R_N 1
        sleep 1
    fi


    for i in $(seq 1 10)
    do
        sleep 1
        if [ "$(power_status)" == "off" ]; then
            return 0
        fi

        if [ "$i" -eq 10 ]; then
            return 1
        fi
    done

}

# Graceful DC off
graceful_power_off() {
    if ! is_host_present; then
        echo "Host not present, skip graceful off."
        return 0
    fi
    if [ "$(power_status)" == "on" ]; then
        set_gpio SYS_BMC_PWRBTN_R_N 0
        sleep 5
        set_gpio SYS_BMC_PWRBTN_R_N 1
        sleep 1

        # wait host power off
        for i in $(seq 1 20)
        do
            sleep 1
            if [ "$(power_status)" == "off" ]; then
               break
            fi
        done
    fi
}

# DC on
power_on() {
    if ! is_host_present; then
        echo "Host not present, skip power on."
        return 0
    fi
    if [ "$(power_status)" == "off" ]; then
        set_gpio SYS_BMC_PWRBTN_R_N 0
        sleep 1
        set_gpio SYS_BMC_PWRBTN_R_N 1
        sleep 1

        for i in $(seq 1 10)
        do
            sleep 1
            if [ "$(power_status)" == "on" ]; then
               return 0
            fi

            if [ "$i" -eq 10 ]; then
               return 1
            fi
        done
    fi
    return 0
}

# Host reset
power_reset() {
    if ! is_host_present; then
        echo "Host not present, skip power reset."
        return 0
    fi
    set_gpio R_BMC_PTH_RST_BTN_L 0
    sleep 1
    set_gpio R_BMC_PTH_RST_BTN_L 1
    sleep 1
    return 0
}
