#!/bin/bash

# Get device index
get_ncsi_dev_idx() {
    ip link show "$1" | awk -F':' 'NR==1 {print $1}'
}

# Bring the interface down and up using 'ip link set "$IFACE" down/up'
# to force the NCSI driver to redo the probe.
# The NCSI driver should support this operation.
check_and_bounce() {
    local IFACE=$1
    local DEV_IDX

    echo "Checking $IFACE ..."

    DEV_IDX=$(get_ncsi_dev_idx "$IFACE")

    ncsi-netlink -x "$DEV_IDX" -p 0 -i
    ret=$?

    if [ $ret -eq 1 ]; then
        echo "NCSI error detected on $IFACE (ret=$ret) → bounce..."
        ip link set "$IFACE" down
        sleep 1
        ip link set "$IFACE" up
        sleep 5
        ip addr
    else
        echo "$IFACE NCSI OK (ret=$ret)"
    fi
}

# On the Anacapa platform, only the NCSI LAN is enabled by default.
# Due to development environment limitations, the dedicated LAN may need to be enabled occasionally.
#   - If both NCSI and dedicated LAN are enabled: eth0 is dedicated LAN, and eth1 is NCSI.
#   - If only NCSI is enabled: eth0 serves as the NCSI interface.
if ip link show eth1 >/dev/null 2>&1 ; then
    check_and_bounce eth1
elif ip link show eth0 >/dev/null 2>&1 ; then
    check_and_bounce eth0
else
    echo "No interface eth1 / eth0 exists"
fi

