#!/bin/sh

ptestdir=$(dirname "$(readlink -f "$0")")
cd tests
for test in $(ls)
do
	./../test-driver --test-name $test --log-file ../$test.log --trs-file ../$test.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./$test
done
