#!/bin/sh
### BEGIN INIT INFO
# Provides:          kea-dhcp4-server
# Required-Start:    $local_fs $network $remote_fs $syslog
# Required-Stop:     $local_fs $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ISC KEA DHCP IPv6 Server
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="kea-dhcp4-server"
NAME=kea-dhcp4
DAEMON=/usr/sbin/kea-dhcp4
DAEMON_ARGS="-c /etc/kea/kea-dhcp4.conf"
PIDFILE=/var/run/kea/kea-dhcp4.kea-dhcp4.pid

set -e

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Source function library.
. /etc/init.d/functions

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon -S -b -n $NAME -p $PIDFILE -x $DAEMON -- $DAEMON_ARGS
        echo "done."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon -K -p $PIDFILE -x $DAEMON
        echo "done."
        ;;
  restart|force-reload)
        #
        $0 stop
        $0 start
        ;;
  status)
        status $DAEMON
        exit $?
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
        exit 1
        ;;
esac
