diff --git a/Makefile b/Makefile
index a55897f..52e1063 100644
--- a/Makefile
+++ b/Makefile
@@ -1,9 +1,7 @@
-CPPFLAGS=$(shell pkg-config --cflags libsystemd)
-LDFLAGS=$(shell pkg-config --libs libsystemd)
+all: btbridged
 
-EXE = btbridged
-
-all: $(EXE)
+btbridged: btbridged.c
+	$(CC) $(CFLAGS) `pkg-config --cflags --libs libsystemd` $^ -o $@
 
 clean:
-	rm -rf *.o $(EXE)
+	rm -f *.o btbridge
