diff --git a/Makefile b/Makefile
index a55897f..73206b4 100644
--- a/Makefile
+++ b/Makefile
@@ -5,5 +5,8 @@ EXE = btbridged
 
 all: $(EXE)
 
+btbridged: btbridged.c
+	$(CC) $(CFLAGS) `pkg-config --cflags --libs libsystemd` $^ -o $@
+
 clean:
 	rm -rf *.o $(EXE)
