diff --git a/Makefile b/Makefile
index 7f62be2..52e1063 100644
--- a/Makefile
+++ b/Makefile
@@ -2,3 +2,6 @@ all: btbridged
 
 btbridged: btbridged.c
 	$(CC) $(CFLAGS) `pkg-config --cflags --libs libsystemd` $^ -o $@
+
+clean:
+	rm -f *.o btbridge
