#!/bin/bash

# Handle chassis and host power state for chassis poweron failure.

CHASSIS_ID=$1

# Stop obmc-chassis-poweron.target to avoid chassis-state-manager to set power state to On.
/bin/systemctl stop obmc-chassis-poweron@"${CHASSIS_ID}".target

# Set chassis power state to Off.
/bin/sh -c "busctl set-property $(mapper get-service /xyz/openbmc_project/state/chassis"${CHASSIS_ID}") \
    /xyz/openbmc_project/state/chassis${CHASSIS_ID} \
    xyz.openbmc_project.State.Chassis CurrentPowerState \
    s xyz.openbmc_project.State.Chassis.PowerState.Off"
