#!/bin/bash

EID=$(($1*10))
count=0

while [ $count -lt 12 ]; do
    busctl get-property xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp/1/"$EID" xyz.openbmc_project.MCTP.Endpoint EID
    isMctpConnect=$?;
    echo $isMctpConnect
    if [ $isMctpConnect -eq 0 ]; then
        echo "MCTP ETD $EID connection successfully."
        sleep 20
        exit 0;
    fi
    echo "MCTP EID $EID not connection yet."
    sleep 5;
    count=$((count + 1))
done

echo "timeout waiting for MCTP EID $EID connection."
exit 1
