#!/bin/bash

EID=$(($1*10))
count=0

while [ $count -lt 12 ]; do
    busctl get-property xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp/1/"$EID" xyz.openbmc_project.MCTP.Endpoint EID
    isMctpConnect=$?;
    echo $isMctpConnect
    if [ $isMctpConnect -eq 0 ]; then
        exit 0;
    fi
    sleep 5;
    count=$((count + 1))
done

echo "timeout waiting for MCTP connection"
exit 1
