#!/bin/sh
#
#This script is used to run qemu test suites
#

ptestdir=$(dirname "$(readlink -f "$0")")
export SRC_PATH=$ptestdir

cd $ptestdir/tests
tests=$(find . -name "test-*" ! -name "*.p")
for f in $tests; do
    $f  | sed '/^ok/ s/ok/PASS:/g'
done
