#!/bin/sh

ptestdir=$(dirname "$(readlink -f "$0")")
cd tests
# omit ssh2.sh until https://github.com/libssh2/libssh2/issues/630 is fixed
for test in simple mansyntax.sh
do
	./../test-driver --test-name $test --log-file ../$test.log --trs-file ../$test.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./$test
done
