OBMC_IMAGE_EXTRA_INSTALL:append = " \
    phosphor-nvme \
    plat-svc \
    motor-ctrl \
    phosphor-virtual-sensor \
    usbutils \
    idevicerestore \
    fw-update \
    phosphor-sel-logger \
    phosphor-gpio-monitor-presence \
    detect-sled-present \
    phosphor-ipmi-ipmb \
    fb-ipmi-oem \
    board-type-checker \
    obmc-phosphor-buttons-signals \
    obmc-phosphor-buttons-handler \
"
