SUMMARY = "Common Information Model (CIM) Schema"
DESCRIPTION = "Common Information Model (CIM) is a model for describing overall\
management information in a network or enterprise environment. CIM\
consists of a specification and a schema. The specification defines the\
details for integration with other management models. The schema\
provides the actual model descriptions."

HOMEPAGE = "http://www.dmtf.org/"
SECTION = "libs"
