#!/bin/bash

EVENT=$1
LOG_LEVEL=$2

DEVICE_PATH="/xyz/openbmc_project/State/chassis0"

busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging \
    xyz.openbmc_project.Logging.Create Create "$EVENT" --json \
                        "{ \"DEVICE\": \"${DEVICE_PATH}\"}" \
                            xyz.openbmc_project.Logging.Entry.Level."$LOG_LEVEL"
