#!/bin/sh

failed=0
all=0


for f in *.test; do
    LD_PRELOAD=$(pwd)/libtestlookup.so ./run $f
    case "$?" in
        0)
            echo "PASS: $f"
            all=$((all + 1))
            ;;
        77)
            echo "SKIP: $f"
            ;;
        *)
            echo "FAIL: $f"
            failed=$((failed + 1))
            all=$((all + 1))
            ;;
    esac
done

if [ "$failed" -eq 0 ] ; then
    echo "All $all tests passed"
    exit 0
else
    echo "$failed of $all tests failed"
    exit 1
fi
