#!/bin/bash

# shellcheck source=meta-facebook/meta-yosemite5/recipes-phosphor/state/phosphor-state-manager/power-cmd
source /usr/libexec/phosphor-state-manager/power-cmd

REQ_OFF="${HOST_STATE_INTF}.Transition.Off"
STATE_TRANS_OFF="${HOST_STATE_INTF}.HostState.TransitioningToOff"

if [ "$(get_host_prop RequestedHostTransition)" = "$REQ_OFF" ]; then
    exit 0
fi

if is_service_busy \
    host-graceful-poweroff@0.service \
    host-force-poweroff@0.service \
    host-powerreset@0.service; then
    exit 0
fi

set_host_prop CurrentHostState "$STATE_TRANS_OFF"
sleep 3
if [ "$(power_status)" = "off" ]; then
    if [ "$(get_host_prop RequestedHostTransition)" != "$REQ_OFF" ]; then
        set_host_prop RequestedHostTransition "$REQ_OFF"
    fi
fi

exit 0
