#!/bin/bash

# shellcheck source=meta-facebook/meta-yosemite5/recipes-phosphor/state/phosphor-state-manager/power-cmd
source /usr/libexec/phosphor-state-manager/power-cmd

# 1. Change to page 3, for r/w regsiter 0x300 ~ 0x3FF
i2ctransfer -y 13 w2@0x09 0xfd 0x03

# 2. Disable SSC
i2ctransfer -y 13 w2@0x09 0x07 0x00

# 3. Setting SSC amplitude + step（-0.25%）
i2ctransfer -y 13 w5@0x09 0x04 0xFC 0x2D 0x28 0x80
i2ctransfer -y 13 w5@0x09 0x04 0xB5 0x16 0x28 0x80

# 4. enable SSC
i2ctransfer -y 13 w2@0x09 0x07 0x80

# 5. Check SSC Enable/Disable status
ret=$(i2ctransfer -y 13 w1@0x09 0x07 r1 2>/dev/null | tr -d ' ')
if [ "$ret" != "0x80" ]; then
    echo "Wrong SSC status read: $ret"
fi
echo "SSC deassertion is triggered by power-good drop, \
    set SSC to -0.25% for better signal integrity"

currentstate=$(busctl get-property \
    xyz.openbmc_project.State.Host0 \
    /xyz/openbmc_project/state/host0 \
    xyz.openbmc_project.State.Host \
    CurrentHostState | awk '{print $2}' | tr -d '"')
if [ "$currentstate" == "xyz.openbmc_project.State.Host.HostState.TransitioningToRunning" ]; then
    exit 0
fi

if is_service_busy host-poweron@0.service; then
    exit 0
fi

if is_service_busy host-powerreset@0.service; then
    exit 0
fi

# Sync power status to "On" for abnormal power-on scenarios.
if [ "$(power_status)" == "on" ]; then
    transition=$(busctl get-property \
        xyz.openbmc_project.State.Host0 \
        /xyz/openbmc_project/state/host0 \
        xyz.openbmc_project.State.Host \
        RequestedHostTransition | awk '{print $2}' | tr -d '"')
    if [ "$transition" != "xyz.openbmc_project.State.Host.Transition.On" ]; then
        busctl set-property xyz.openbmc_project.State.Host0 \
            /xyz/openbmc_project/state/host0 \
            xyz.openbmc_project.State.Host \
            RequestedHostTransition s \
            xyz.openbmc_project.State.Host.Transition.On
    elif [ "$currentstate" == "xyz.openbmc_project.State.Host.HostState.TransitioningToOff" ]; then
        busctl set-property xyz.openbmc_project.State.Host0 \
            /xyz/openbmc_project/state/host0 \
            xyz.openbmc_project.State.Host \
            CurrentHostState s xyz.openbmc_project.State.Host.HostState.Off
        sleep 0.1
        busctl set-property xyz.openbmc_project.State.Host0 \
            /xyz/openbmc_project/state/host0 \
            xyz.openbmc_project.State.Host \
            CurrentHostState s xyz.openbmc_project.State.Host.HostState.Running
    fi
fi

exit 0
