#!/bin/bash

# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions

host_os_status_init() {
  local status

  if [ "$(get_gpio host0-ready)" -eq 0 ]; then
      status="Standby"
  else
      status="Inactive"
  fi

  busctl set-property \
      xyz.openbmc_project.State.Host0 \
      /xyz/openbmc_project/state/host0 \
      xyz.openbmc_project.State.OperatingSystem.Status \
      OperatingSystemState s \
      "xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.${status}"
}

e1s_board_init() {
  if [[ "$(get_gpio RST_PCIE_BOOT_PERST_N)" = "0" ]]; then
    set_gpio RST_PCIE_E1S_0_PERST 0
    set_gpio RST_PCIE_E1S_1_PERST 0
  else
    set_gpio RST_PCIE_E1S_0_PERST 1
    set_gpio RST_PCIE_E1S_1_PERST 1
  fi

  e1s_0_prsnt=$(get_gpio E1S_0_PRSNT_N)
  if [[ "$e1s_0_prsnt" = "0" ]]; then
    set_gpio P12V_E1S_EN_0 1
  else
    set_gpio P12V_E1S_EN_0 0
  fi

  e1s_1_prsnt=$(get_gpio E1S_1_PRSNT_N)
  if [[ "$e1s_1_prsnt" = "0" ]]; then
    set_gpio P12V_E1S_EN_1 1
  else
    set_gpio P12V_E1S_EN_1 0
  fi
}

host_os_status_init

e1s_board_init

exit 0
