#!/bin/bash

# shellcheck source=meta-facebook/recipes-fb/obmc_functions/files/fb-common-functions
source /usr/libexec/fb-common-functions

host_os_status_init() {
  local status

  if [ "$(get_gpio host0-ready)" -eq 0 ]; then
      status="Standby"
  else
      status="Inactive"
  fi

  busctl set-property \
      xyz.openbmc_project.State.Host0 \
      /xyz/openbmc_project/state/host0 \
      xyz.openbmc_project.State.OperatingSystem.Status \
      OperatingSystemState s \
      "xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.${status}"
}

e1s_pwr_init() {
  reg0=$(i2ctransfer -fy 10 w1@0x21 0x0 r1)
  reg1=$(i2ctransfer -fy 10 w1@0x21 0x1 r1)
  E1S_0_PRSNT_N=$(( reg0 & 0x04 ))
  E1S_1_PRSNT_N=$(( reg1 & 0x04 ))
  if [[ "$E1S_0_PRSNT_N" = "0" && "$(get_gpio MASTER_PWR2_EN)" = "1" ]]; then
    set_gpio P12V_E1S_EN_0 1
  else
    set_gpio P12V_E1S_EN_0 0
  fi

  if [[ "$E1S_1_PRSNT_N" = "0" && "$(get_gpio MASTER_PWR2_EN)" = "1" ]]; then
    set_gpio P12V_E1S_EN_1 1
  else
    set_gpio P12V_E1S_EN_1 0
  fi
}

host_os_status_init

e1s_pwr_init

exit 0
