#!/bin/bash
# shellcheck source=meta-facebook/meta-yosemite5/recipes-yosemite5/plat-tool/files/yosemite5-common-functions
source /usr/libexec/yosemite5-common-functions

input="$1"

if [ "$input" == "RISING" ] ; then
    set_gpio SGPIO_RSTBTN_OUT       0
elif [ "$input" == "FALLING" ] ; then
    set_gpio SGPIO_RSTBTN_OUT       1
fi