.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH IASL 1 "October 14, 2005"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
iasl \- ACPI Source Language compiler/decompiler
.SH SYNOPSIS
.B iasl
.RI [ options ]
.RI [ "input file" ]
.SH DESCRIPTION
This manual page documents briefly the
.B iasl
command. The option list is taken from the iasl interactive help.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.B iasl
is an ASL compiler and decompiler.

.SH OPTIONS

.PP
.SS General Output
.TP
.B \-p <prefix>
Specify filename prefix for all output files (including .aml)
.TP
.B \-vi
Less verbose errors and warnings for use with IDEs
.TP
.B \-vo
Enable optimization comments
.TP
.B \-vr
Disable remarks
.TP
.B \-vs
Disable signon

.PP
.SS AML Output Files
.TP
.B \-s<a|c>
Create AML in assembler or C source file (*.asm or *.c)
.TP
.B \-i<a|c>
Create assembler or C include file (*.inc or *.h)
.TP
.B \-t<a|c>
Create AML in assembler or C hex table (*.hex)

.PP
.SS AML Code Generation
.TP
.B \-oa
Disable all optimizations (compatibility mode)
.TP
.B \-of
Disable constant folding
.TP
.B \-oi
Disable integer optimization to Zero/One/Ones
.TP
.B \-on
Disable named reference string optimization
.TP
.B \-r<Revision>
Override table header Revision (1-255)

.PP
.SS Listings
.TP
.B \-l
Create mixed listing file (ASL source and AML) (*.lst)
.TP
.B \-ln
Create namespace file (*.nsp)
.TP
.B \-ls
Create combined source file (expanded includes) (*.src)

.PP
.SS AML Disassembler
.TP
.B \-d  [file]
Disassemble AML to ASL source code file (*.dsl)
.TP
.B \-dc [file]
Disassemble AML and immediately compile it
.br
(Obtain DSDT from current system if no input file)
.TP
.B \-e
Generate External() statements for unresolved symbols
.TP
.B \-g
Get ACPI tables and write to files (*.dat)

.PP
.SS Miscellaneous
.TP
.B \-a
Verify source file is entirely ASCII text (0x00-0x7F)

.PP
.SS Help
.TP
.B \-h
Additional help and compiler debug options
.TP
.B \-hc
Display operators allowed in constant expressions
.TP
.B \-hr
Display ACPI reserved method names

.SH AUTHOR
iasl was written by Robert Moore <robert.moore@intel.com>.
.PP
This manual page was written by Mattia Dongili <malattia@debian.org>,
for the Debian project (but may be used by others).
