#!/bin/sh

for case in `find t -type f -name '*.t'`; do
    perl -I inc -I blib -Mblib $case >$case.output 2>&1
    ret=$?
    cat $case.output
    if [ $ret -ne 0 ]; then
        echo "FAIL: ${case%.t}"
    else
        echo "PASS: ${case%.t}"
    fi

    rm -f $case.output
done
