#!/bin/bash

# shellcheck source=meta-facebook/meta-harma/recipes-phosphor/gpio/phosphor-gpio-monitor/auto-power
source /usr/libexec/phosphor-gpio-monitor/auto-power

# End the script if the FRU version is DVT1 and triggered by SGPIO18
if ! check-auto-power-condition "$1"; then
    exit 0
fi

sleep 1

# Set Host Power On
obmcutil poweron

# Turn on the power Led
systemctl start obmc-led-group-start@power_on.service
