OBMC_IMAGE_EXTRA_INSTALL_append_gsj = " quanta-nvme-powerctrl"
OBMC_IMAGE_EXTRA_INSTALL_append_gsj = " phosphor-nvme"
OBMC_IMAGE_EXTRA_INSTALL_append_gsj = " phosphor-pid-control"
OBMC_IMAGE_EXTRA_INSTALL_append_gsj = " detect-fan-fail"
OBMC_IMAGE_EXTRA_INSTALL_append_gsj = " google-ipmi-sys"
OBMC_IMAGE_EXTRA_INSTALL_append_gsj = " gsj-hotswap-change-setting"
OBMC_IMAGE_EXTRA_INSTALL_append_gsj = " iperf3"
IMAGE_FEATURES_remove_gsj = "obmc-user-mgmt-ldap"
