OBMC_IMAGE_EXTRA_INSTALL:append:gsj = " quanta-nvme-powerctrl"
OBMC_IMAGE_EXTRA_INSTALL:append:gsj = " phosphor-nvme"
OBMC_IMAGE_EXTRA_INSTALL:append:gsj = " phosphor-pid-control"
OBMC_IMAGE_EXTRA_INSTALL:append:gsj = " detect-fan-fail"
OBMC_IMAGE_EXTRA_INSTALL:append:gsj = " google-ipmi-sys"
OBMC_IMAGE_EXTRA_INSTALL:append:gsj = " gsj-hotswap-change-setting"
OBMC_IMAGE_EXTRA_INSTALL:append:gsj = " iperf3"
IMAGE_FEATURES:remove:gsj = "obmc-user-mgmt-ldap"
