#!/bin/bash

# shellcheck source=meta-facebook/meta-catalina/recipes-phosphor/state/phosphor-state-manager/power-cmd
source /usr/libexec/phosphor-state-manager/power-cmd

if ! host_force_power_off; then
    exit 1
fi

exit 0
