#!/bin/bash
# shellcheck source=meta-facebook/meta-yosemite5/recipes-yosemite5/plat-tool/files/yosemite5-common-functions
source /usr/libexec/yosemite5-common-functions

set_product_versions_to_mb_cpld()
{
    printf "Setting board product version to MB CPLD\n"

    local BUS="11"
    local ADDR="0x0f"
    declare -A REGS=( ["17"]=0x88 ["18"]=0x88 )

    local BOARD_CONFIGS=(
        "E1_S:17:16"
        "SCM:17:1"
        "Victoria_Falls:18:16"
        "Maple_Falls:18:1"
    )

    for CONFIG in "${BOARD_CONFIGS[@]}"; do
        local BOARD REG MULT
        IFS=":" read -r BOARD REG MULT <<< "$CONFIG"

        local FRU_NAME
        if ! FRU_NAME=$(find_fru_name "$BOARD"); then
            continue
        fi

        local VERSION
        VERSION=$(get_product_version "$FRU_NAME")
        if [ "$VERSION" = "Unknown" ]; then
            continue
        fi

        local STAGE_VAL
        case "$VERSION" in
            EVT)      STAGE_VAL=0 ;;
            DVT|DVT1) STAGE_VAL=1 ;;
            DVT2)     STAGE_VAL=2 ;;
            DVT3)     STAGE_VAL=3 ;;
            PVT)      STAGE_VAL=4 ;;
            MP)       STAGE_VAL=5 ;;
            *)        continue ;;
        esac

        local MASK=$(( 0x0F * MULT ))
        local VAL=$(( STAGE_VAL * MULT ))
        REGS["$REG"]=$(( (REGS["$REG"] & ~MASK) | VAL ))

        printf "Found %s version: %s\n" "$FRU_NAME" "$VERSION"
    done

    for REG in "${!REGS[@]}"; do
        local VAL_HEX
        VAL_HEX=$(printf "0x%02x" "${REGS[$REG]}")

        if ! i2cset -y "$BUS" "$ADDR" "0x$REG" "$VAL_HEX" 2>/dev/null; then
            printf "MB CPLD Reg 0x%s: Write failed\n" "$REG"
            continue
        fi

        local READ_VAL
        READ_VAL=$(i2cget -y "$BUS" "$ADDR" "0x$REG" 2>/dev/null)

        if [ -z "$READ_VAL" ]; then
            printf "MB CPLD Reg 0x%s: Read back failed\n" "$REG"
        elif [ "$((READ_VAL))" -ne "$((VAL_HEX))" ]; then
            printf "MB CPLD  Reg 0x%s: Mismatch (W:%s R:%s)\n" \
                "$REG" "$VAL_HEX" "$READ_VAL"
        else
            printf "MB CPLD Reg 0x%s: Updated to %s\n" "$REG" "$VAL_HEX"
        fi
    done
}

set_product_versions_to_mb_cpld

echo "initial value for GPIO output pins"
# set initial value for GPIO output pins

# A0-A7
# B0-B7
set_gpio BMC_READY    1
# D0-D7
# E0-E7
# F0-F7
# G0-G7
# H0-H7
# I0-I7
# M0-M7
# N0-N7
# O0-O7
# P0-P7
# Q0-Q7
# R0-R7
# S0-S7
# T0-T7
# U0-U7
# V0-V7

# set initial value for IOEXP GPIO output pins

# MB IOEXP
set_gpio FM_CLKMUX_0_SEL 1
set_gpio FM_CLKMUX_1_SEL 1
set_gpio FM_CLKMUX_2_SEL 1
set_gpio FM_CLKMUX_3_SEL 1
set_gpio FM_CLKGEN_GPIO2 1
set_gpio FM_CLKGEN_GPIO4 0
set_gpio RST_USB_HUB_0_N 1

# SGPIO
set_gpio SGPIO_RSTBTN_OUT 0
set_gpio IBB_BMC_SRST 1
set_gpio FM_I3C_SPD_AH_SEL_R 0
set_gpio FM_I3C_SPD_IP_SEL_R 0
set_gpio FM_JTAG_BMC_MUX_S0_R 0
set_gpio FM_JTAG_BMC_MUX_S1_R 0
set_gpio FM_JTAG_BMC_OE_1_R_N 1
set_gpio FM_JTAG_BMC_OE_R_N 1
set_gpio FM_REMOTEJTAG_EN_R_N 1
set_gpio FM_CPU_FORCE_SELFREFRESH_R 0
set_gpio FM_CPU_NMI_SYNC_FLOOD_R_N 1
set_gpio FM_CPU_TRIGGERTSC_OE_R_N 1
set_gpio FM_PASSWORD_CLEAR_R_N 1
set_gpio FM_BIOS_USB_RECOVERY_N 1
set_gpio FM_USB_MUX_OE_R_N 1
set_gpio FM_USB_MUX_SEL_R 0
set_gpio RST_SMB_BOOT_R_N 1
set_gpio RST_SMB_MCIO0A_R_N 1
set_gpio RST_SMB_NIC_R_N 1
set_gpio FM_PPS_NIC_IN_BUF_OE_R_N 1
set_gpio FM_PPS_NIC_IN_EN_R 0
set_gpio FM_PPS_NIC_IN_OE_R_N 1
set_gpio FM_PPS_NIC_IN_S0_R 0
set_gpio FM_PPS_NIC_IN_S1_R 0
set_gpio FM_PPS_NIC_OUT_BUF_OE_R_N 1
set_gpio FM_PPS_NIC_OUT_CPU_OE_R_N 1
set_gpio FM_PPS_NIC_OUT_EN_R 0
set_gpio JTAG_CPLD_DBREQ_R_N 1
set_gpio HDT_HDR_RESET_R_N 1
set_gpio FM_SMB_AUTH_MUX_OE_R_N 1
set_gpio FM_SCM_LED_R_N 1
set_gpio SGPIO_BMC_READY 1

exit 0
