#! /bin/sh

cd testsuite

failed=0
all=0

for f in *-test; do
    case "$f" in
        "sha1-huge-test")
            echo "SKIP: $f (long run time)"
            ;;
        "symbols-test")
            echo "SKIP: $f (needs static libraries)"
            ;;
        *)
            "./$f"
            case "$?" in
                0)
                    echo "PASS: $f"
                    all=$((all + 1))
                    ;;
                77)
                    echo "SKIP: $f"
                    ;;
                *)
                    echo "FAIL: $f"
                    failed=$((failed + 1))
                    all=$((all + 1))
                    ;;
            esac
            ;;
    esac
done

if [ "$failed" -eq 0 ] ; then
    echo "All $all tests passed"
else
    echo "$failed of $all tests failed"
fi
