MACHINEOVERRIDES =. "p10bmc:"

require conf/machine/include/ibm-enterprise.inc
require conf/machine/p10bmc.conf
require conf/distro/include/phosphor-no-ipmi-rmcp.inc

DEBUG_TRIGGERS = "kcs2"
PACKAGECONFIG:append:pn-debug-trigger = " triggers"

IMAGE_FEATURES:remove = "obmc-host-ipmi"
