#!/bin/sh

ptestdir=$(dirname "$(readlink -f "$0")")
cd "$ptestdir"/tests || exit

tests=$(find * -type f -name 'tdb1-*')

for f in replace_testsuite $tests
do
    if test -x ./"$f"; then
        if ./"$f" > ./"$f".out 2> ./"$f".err; then
            echo "PASS: $f"
        else
            echo "FAIL: $f"
        fi
    fi
done
