# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rainiera6-layer"
BBFILE_PATTERN_rainiera6-layer := "^${LAYERDIR}/"

LAYERSERIES_COMPAT_rainiera6-layer := "wrynose whinlatter"
